In [1]:
# Import Libraries
import pandas as pd
from bs4 import BeautifulSoup
import requests
import smtplib
from datetime import time, datetime, timedelta
import random, re

# Global Variables
global bullet_characters 
global salary_descriptors 
bullet_characters = ['-', '•', '◦', '▪', '▸', '➤', '★', '*']
salary_descriptors = ['$','pay','paid','salary','compensation']

In [2]:
# Extract HTML - Paginated Func
def extract(page):    
    url = f'https://www.teamworkonline.com/jobs-in-sports?employment_opportunity_search%5Bsort_by%5D=most_recent&page={page}'
    user_agents_list = [
    'Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36',
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"]
    
    headers = {'User-Agent': random.choice(user_agents_list)}

    page = requests.get(url,headers = headers)

    soup = BeautifulSoup(page.content,'html.parser')
    return(soup)

In [3]:
# Extract HTML - Inner Link (a tag) Func
def extract_inner(url):    
    user_agents_list = [
    'Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36',
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"]
    
    headers = {'User-Agent': random.choice(user_agents_list)}

    page = requests.get(url,headers = headers)

    soup = BeautifulSoup(page.content,'html.parser')
    return(soup)

In [195]:
def transform(jobs_soup):
    all_jobs = jobs_soup.find_all(class_ = "browse-jobs-card")
    raw_jobs = []
    for job in all_jobs:
##################################################################### Scraping Basic info from Job cards ############################################################################
        try:
            raw_job={
                'logo_image': job.find('img').get('src') if job.find('img') else None,
                'job_url': 'https://www.teamworkonline.com' + job.find('a').get('href') if job.find('a') else None,
                'title': job.find(class_ = "margin-none").get_text().strip() if job.find(class_ = "margin-none") else None,
                'company': job.find(class_ = "browse-jobs-card__content--organization").get_text().strip() if job.find(class_ = "browse-jobs-card__content--organization") else None,
                'location_info': job.find(class_ = "trending__content--small").get_text().strip() if job.find(class_ = "trending__content--small") else None,
                'experience_level': job.find(class_ = "browse-jobs-card__content--small").get_text().strip() if job.find(class_ = "browse-jobs-card__content--small") else None  
            }
####################################################################### Extracting info from the individual job site #################################################################     
            job_soup = extract_inner(raw_job['job_url'])
            raw_job['salary_info'] = salary_fetcher(job_soup)
            raw_job['details'] = detail_fetcher(job_soup)
                       
################################################### Scraping time based info from Job cards and doing minor extractions  #############################################################    
            posting_number_list = job.find_all(class_ = "browse-jobs-card__scoreboard")
            if len(posting_number_list)>= 2:
                raw_job['posting_numbers'] = posting_number_list[0].get_text().strip() + posting_number_list[1].get_text().strip()
            else:
                raw_job['posting_numbers'] = None
            raw_job['posting_date_identifier'] = job.find(class_ = "trending__content--small trending__scoreboard--time margin-left--xx-small").get_text().strip().split(' ')[0]
            raw_job['scrape_datetime'] = datetime.now()
            
            jobs_list.append(raw_job)
            
        except Exception as e:
            print(f"Error during job scrape: {e}")
            continue
    return

In [193]:
job_posting = {}
job_soup = extract_inner('https://www.teamworkonline.com/hockey-jobs/hockeyjobs/nhl-league-office/royalty-analyst-2163333')
job_posting['salary_info'] = salary_fetcher(job_soup)
job_posting['details'] = detail_fetcher(job_soup)

Need to Standardize Divs
<p>The royalty analyst will be responsible for the day-to-day processing of consumer products royalty statements. Tasks include:</p>



<p>Required</p>



<p>Preferred</p>



<p>Education/Certifications</p>



<p>Required Skills</p>



<p>These core competencies reflect the underlying values that are necessary to represent the National Hockey League:</p>

In [194]:
job_posting

{'salary_info': '$60,000 - $63,000 / year',
 'details':   The royalty analyst will be responsible for the day-to-day processing of consumer products royalty statements. Tasks include:  \
 0        Processing statements in the royalty system
 1  Reviewing royalties reported for assigned lice...
 2  Analyzing revenue generated from royalty state...
 3  Reviewing and applying cash received from lice...
 4  Communicate with licensees regarding their roy...
 5  Assisting with the preparation of royalty repo...
 6  Assist with testing new releases of the royalt...
 7                            Ad hoc special projects

                           Required  \
 0  Advanced Microsoft Excel skills
 1                              NaN
 2                              NaN
 3                              NaN
 4                              NaN
 5                              NaN
 6                              NaN
 7                              NaN

                                            Preferred  \
 0  Experience with consumer products licensing an...
 1                                                NaN
 2                                                NaN
 3                                                NaN
 4                                                NaN
 5                                                NaN
 6                                                NaN
 7                                                NaN

                             Education/Certifications  \
 0  Minimum of Bachelor’s degree, Accounting or Fi...
 1                                                NaN
 2                                                NaN
 3                                                NaN
 4                                                NaN
 5                                                NaN
 6                                                NaN
 7                                                NaN

                                      Required Skills  \
 0                Excellent verbal and written skills
 1  Strong analytical and organizational skills an...
 2       Able to handle multiple tasks simultaneously
 3  Take initiative and develop creative solutions...
 4                                                NaN
 5                                                NaN
 6                                                NaN
 7                                                NaN

   These core competencies reflect the underlying values that are necessary to represent the National Hockey League:
 0                                     Accountability
 1                                       Adaptability
 2                                      Communication
 3                                  Critical Thinking
 4                                          Inclusion
 5                                    Professionalism
 6                           Teamwork & Collaboration
 7                                                NaN                                                                 }

In [199]:
# This is code to find salary in the top portion of the sit
def salary_fetcher(job_soup):
    salary_desc = None
    try:
        salary_flag = job_soup.find_all('div',class_ = 'margin-right--x-small')
        for i in range(0,len(salary_flag)):
            if any(descriptor in str(salary_flag[i]) for descriptor in salary_descriptors):
                salary_desc = salary_flag[i].get_text()
                #print(salary_flag[i].get_text())
            else:
                pass
    except Exception as e:
        print(f"Error during job scrape: {e}")
    return(salary_desc)

In [179]:
####################################### THIS IS THE NEW APPROACH AS OF 3/17 ##############################################
#text = "This is a sample test to see what will happen to be honest: \n\n\n- This is bullet 1.\n\n\n\n- This is bullet 2.\n- This is bullet 3.\n- This is bullet 4.\n- This is bullet 5. \n This is extra text Now that Idk what will happen to."

def wrap_bullets(html_text):
    if(html_text.find('ul')):
        for ul in html_text.find_all('ul'):
            for li in ul:
                li.string = '- ' + li.get_text()
    else:
        pass
    
    text = html_text.get_text(separator = '\n')
    
    lines = text.split('\n')
    result = []
    in_list = False
    
    for line in lines:
        stripped_line = line.strip()
        
        if in_list and stripped_line == '':
            continue
    
        if stripped_line and stripped_line[0] in bullet_characters:
            if not in_list:
                preceding_line = next((line for line in reversed(result) if line.strip()), None)
                result.append(f'<p>{preceding_line}</p>')
                result.append('<ul>')
                in_list = True
            content = stripped_line[1:].strip()
            result.append(f'<li>{content}</li>')
        else:
            if in_list:
                result.append('</ul>')
                in_list = False
            result.append(stripped_line)
            
    if in_list:
        result.append('</ul>')
    
    final_result = '\n'.join(result)
    
    soup = BeautifulSoup(final_result,'html.parser')

    return(soup.find_all('p'))

In [203]:
def detail_fetcher(job_soup):
    try:
        job_inner = job_soup.find('div', class_='opportunity-preview__body')
        job_details = job_inner.find_all('p')
        
        if job_details:
            if job_inner.find('ul'):
                print('Standard HTML')
                p_tag = True
            else:
                p_tag = False
                print('Need to standardize Ps')
        else:
            p_tag = False
            print('Need to Standardize Divs')
        
        if (p_tag):
            pass
        else:
            job_details = wrap_bullets(job_inner)
        
        data = {}
        headers = []
        for section in job_details:
            
            if not section:
                continue
            
            details = []
                
            header_text = section.get_text()
            next_tag = section.find_next_sibling()
            
            if (next_tag and next_tag.name in ['ul', 'ol']):
                headers.append(header_text)
                items = next_tag.find_all('li')
                details = [item.get_text(strip=True) for item in items]
            
                data[header_text] = details 
                    
        
        # Convert to single-row DataFrame
        details_df = pd.DataFrame({k: pd.Series(v) for k, v in data.items()})
    except:
        details_df = []
    return(details_df)

In [181]:
headers

['The royalty analyst will be responsible for the day-to-day processing of consumer products royalty statements. Tasks include:',
 'Required',
 'Preferred',
 'Education/Certifications',
 'Required Skills',
 'These core competencies reflect the underlying values that are necessary to represent the National Hockey League:']

In [182]:
# CODE TO PULL OFF RELEVANT INFO FROM DETAIL SCRAPE
df.filter(regex = '(?i)requ|respon|qual|look|skill|know|job|function|Elig|edu|exper|duties|duty',axis=1)

,The royalty analyst will be responsible for the day-to-day processing of consumer products royalty statements. Tasks include:,Required,Education/Certifications,Required Skills
0,Processing statements in the royalty system,Advanced Microsoft Excel skills,"Minimum of Bachelor’s degree, Accounting or Fi...",Excellent verbal and written skills
1,Reviewing royalties reported for assigned lice...,NaN,NaN,Strong analytical and organizational skills an...
2,Analyzing revenue generated from royalty state...,NaN,NaN,Able to handle multiple tasks simultaneously
3,Reviewing and applying cash received from lice...,NaN,NaN,Take initiative and develop creative solutions...
4,Communicate with licensees regarding their roy...,NaN,NaN,NaN
5,Assisting with the preparation of royalty repo...,NaN,NaN,NaN
6,Assist with testing new releases of the royalt...,NaN,NaN,NaN
7,Ad hoc special projects,NaN,NaN,NaN

In [183]:
details_df = []
for header in headers:
    details_df.append({header: df[header].str.split('\n').explode(header)})
details_df = pd.DataFrame(details_df)
details_df

,The royalty analyst will be responsible for the day-to-day processing of consumer products royalty statements. Tasks include:,Required,Preferred,Education/Certifications,Required Skills,These core competencies reflect the underlying values that are necessary to represent the National Hockey League:
0,0 Processing statements in the royalt...,NaN,NaN,NaN,NaN,NaN
1,NaN,0 Advanced Microsoft Excel skills 1 ...,NaN,NaN,NaN,NaN
2,NaN,NaN,0 Experience with consumer products licensi...,NaN,NaN,NaN
3,NaN,NaN,NaN,"0 Minimum of Bachelor’s degree, Accounting ...",NaN,NaN
4,NaN,NaN,NaN,NaN,0 Excellent verbal and writte...,NaN
5,NaN,NaN,NaN,NaN,NaN,0 Accountability 1 ...

In [200]:
# Will use this once deployed pages = (1,11)
pages = ((1,3))
jobs_list = []
for page in range(pages[0],pages[1]):
    recent_jobs_html = extract(page)
    transform(recent_jobs_html)

Need to Standardize Divs
<p>Figure Skating Business Operations &amp; Innovation</p>



<p>advancements, skating industry partnerships, standardizing processes)</p>



<p>Impact 2030</p>



<p>successful candidate.</p>



Standard HTML
<p><strong>Company Information</strong><br/>For more than 20 years, AEG has played a pivotal role in transforming sports and live entertainment. Annually, we host more than 160 million guests, promote more than 10,000 shows and present more than 22,000 events around the world. We are committed to innovation, artistry, and community, and leverage the power of our 300+ venues, leading sports franchises, marquee music brands, integrated entertainment districts, premier ticketing platform and global sponsorship activations, to create memorable moments that give the world reason to cheer.<br/><br/>Our business is interwoven with the human mind and heart, and we strive to build a diverse and inclusive company that reflects the artists, athletes, and fans that we host; reach beyond traditional boundaries to support the communities in which we operate; and minimize our impact on the environment by adopting sustainable practices throughout our business operations.<br/><br/>If you want to be challenged to up your game and make a difference, then join us in giving the world reason to cheer!</p>



<p><strong>Job Summary </strong></p>



<p>The Creative Services Coordinator supports the Creative Services team at AEG Presents by ensuring smooth day to day operations and providing essential administrative and creative support.</p>



<p><strong>Essential Functions </strong></p>



<p><strong>Required Qualifications</strong></p>



<p><strong>Payscale: $22.94/hour - $31.25/hour</strong></p>



<p><strong>Bonus: </strong><em>This position is not eligible for a bonus under the current bonus plan requirements.</em></p>



<p><strong>Benefits:</strong><em><strong> Full-time: </strong>We offer a comprehensive benefits package that includes: medical, dental and vision insurance, paid holidays, vacation and sick time, company paid basic life insurance, voluntary life insurance, parental leave, 401k Plan (with a current employer match of 3%), flexible spending and health savings account options, and wellness offerings.</em></p>



<p>AEG reserves the right to change or modify the employee’s job description whether orally or in writing, at any time during the employment relationship.  AEG may require an employee to perform duties outside their normal description.</p>



<p>AEG's policy is to hire the most qualified applicants, and we comply with all applicable federal, state and local employment laws in making hiring and employee decisions.  We are an equal opportunity employer and do not discriminate against applicants or employees on the basis of race, color, marital status, disability, religion, age, sex, sexual orientation, national origin, genetic information, veteran status, or any other legally protected status recognized by applicable federal, state or local law.</p>



<p> </p>



<p>Employer does not offer work visa sponsorship for this position.</p>



Need to Standardize Divs
Need to Standardize Divs
<p>Why join our team?</p>



<p>The position will:</p>



<p>We believe you have what it takes to make a great impact!</p>



Standard HTML
<p>POSITION: Executive Sous Chef                  </p>



<p>DEPARTMENT: Food and Beverage        </p>



<p>REPORTS TO: Executive Chef  </p>



<p>FLSA STATUS: Salaried, Exempt           </p>



<p></p>



<p>LEGENDS GLOBAL</p>



<p>Legends Global is the premier partner to the world's greatest live events, venues, and brands. We deliver a fully integrated solution of premium services that keeps our partners front and center through our white-label approach.</p>



<p></p>



<p>Our network of 450 venues worldwide, hosting 20,000 events and entertaining 165 million guests each year, is powered by our depth of expertise and level of execution across every component — feasibility &amp; consulting, owner’s representation, sales, partnerships, hospitality, merchandise, venue management, and content &amp; booking — of world-class live events and venues.</p>



<p></p>



<p>The Legends Global culture is one of respect, ambitious thinking, collaboration, and bold action. We are committed to building an inclusive workplace where everyone can be authentic, make an impact, and grow their career.</p>



<p></p>



<p>Winning is an everyday thing at Legends Global. We have the best team members who understand every win is earned when we come together as one unified team. Sound like a winning formula for you? Join us!</p>



<p></p>



<p>THE ROLE</p>



<p>Responsible for managing/overseeing production, operation, and sanitation aspects of all culinary and stewarding operations throughout Mayo Civic Center.</p>



<p></p>



<p>ESSENTIAL DUTES AND RESPONSIBILITIES</p>



<p>People and products focused hands-on management of day-to-day operations of all food outlet kitchens. </p>



<p>Implement and enforce all departmental and organizational policies and procedures. </p>



<p>Ensure staff compliance with all standards, policies and procedures. </p>



<p>Ensure recipe compliance and quality control are met throughout the production process.</p>



<p>Manage associates utilizing Sous Chefs and Lead Cooks through planning and scheduling of work assignments and performance development. Administer corrective counseling processes, training and development, appraisals, payroll accountability. </p>



<p>Maintain communications with food and beverage operations team through weekly meetings and daily conversations to ensure proper menu productions, standards, quality, and number of staff.</p>



<p>Inspect all locations to observe quality of food preparation and service, food appearance, and cleanliness and sanitation of production and service areas</p>



<p>Plan innovative menus for both catering and concessions, maintaining financial responsibility for the menu mix. Analyze menu and food costs and the preparation of cost and quality efficient menus/specials. Prepare reports regarding food and menu analysis. </p>



<p>Prepare cost-saving annual budgets and ensure all fiscal responsibilities are met. </p>



<p>Oversee inventory management to ensure all outlets are always adequately supplied. Perform periodic inventory. Track waste and spoilage. </p>



<p>Oversee requisitioning and purchasing. Maintain effective vendor relationships. </p>



<p>Oversee the sanitation standards of all kitchens to assure compliance with local health department standards and company standards. </p>



<p>Direct interaction with high level clients </p>



<p>Perform related duties as assigned by Management.</p>



<p></p>



<p>QUALIFICATIONS </p>



<p>To perform this job successfully, an individual must be able to perform each essential duty with energy and enthusiasm. The requirements listed below are representative of the knowledge, skill, and/or ability required. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions.</p>



<p></p>



<p>EDUCATION AND/OR EXPERIENCE     </p>



<p>The ideal team member will have a degree or certification from an accredited culinary arts institute, or apprenticeship certification from the American Culinary Federation. </p>



<p>At least three (3) to five (5) years of experience as an executive sous chef in a high-volume food industry. </p>



<p>Proven track record in improving kitchen efficiencies, quality, food and labor costs. </p>



<p>Must have excellent managerial, financial analysis, team building and communication skills/customer service. </p>



<p>Must have knowledge of kitchen sanitation, operation and maintenance of kitchen equipment. </p>



<p>Must be detail-oriented and extremely organized with the ability to learn new programs and procedures quickly. </p>



<p>Must be proficient in Microsoft Word, Excel, and PowerPoint. </p>



<p>Must be flexible to work extended hours due to business requirements including nights, weekends and holidays. </p>



<p>Must be open to providing incidental or short-term support to other facilities in the event of a business emergency. </p>



<p>Travel may be required.    </p>



<p></p>



<p>LICENSES AND CERTIFICATIONS</p>



<p>Serv Safe certified/Food Handlers Certificate</p>



<p></p>



<p>COMPENSATION</p>



<p>Competitive salary, commensurate with experience, and a generous benefits package that includes medical, dental, vision, life and disability insurance, paid vacation, and 401k plan.</p>



<p>Salary: $75,000.00 - $80,000.00</p>



<p></p>



<p>WORKING CONDITIONS</p>



<p>Location: On Site in Rochester, MN</p>



<p></p>



<p>PHYSICAL DEMANDS</p>



<p>The physical demands described here are representative of those that must be met by an employee to successfully perform the essential functions of this job. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions.</p>



<p></p>



<p>NOTE:</p>



<p>The essential responsibilities of this position are described under the headings above. They may be subject to change at any time due to reasonable accommodation or other reasons. Also, this document in no way states or implies that these are the only duties to be performed by the employee occupying this position.</p>



<p></p>



<p>Legends Global is an Equal Opportunity/Affirmative Action employer, and encourages Women, Minorities, Individuals with Disabilities, and protected Veterans to apply. VEVRAA Federal Contractor.</p>

Standard HTML
<p>Job Title: Sales Manager</p>



<p>Department: Sales &amp; Services</p>



<p>Reports To: Assistant Director of Sales</p>



<p>Supervises: None</p>



<p>FLSA Status: Salaried, Exempt</p>



<p></p>



<p>Why the Colorado Convention Center is a great place to work:</p>



<p>$500 Signing Bonus after 30 days of service and an additional $500 bonus upon successful completion of 90 days of service!</p>



<p>Generous Paid Time Off and Holiday Pay</p>



<p>Health, dental, vision insurance, eligible upon hire</p>



<p>401(k) investment plan, with an employer match of up to 4%</p>



<p>Healthcare reimbursement and flexible spending plans</p>



<p>Employer-paid and supplemental life insurance</p>



<p>Short- and long-term disability insurance available</p>



<p>RTD Eco Pass: As a Full-time employee the Colorado Convention Center currently offers an RTD Eco Pass.</p>



<p>Tuition reimbursement program</p>



<p>Employee assistance program</p>



<p></p>



<p>Compensation: Compensation is dependent on experience and ranges from $59,400 - $63,000.</p>



<p></p>



<p>General Summary:</p>



<p>As a Sales Manager, you will focus on cultivating strong client relationships, negotiating contracts, and ensuring seamless collaboration to support successful events.</p>



<p></p>



<p>Primary Duties and Responsibilities:</p>



<p>Maintain the booking calendar, manage correspondence, and ensure seamless follow-through on communications.</p>



<p>Handle sales and contracting for event business generated by internal leads and VISIT DENVER-booked clients.</p>



<p>Execute contract procedures, including negotiations, revisions, and amendments, in compliance with ASM GLOBAL policies.</p>



<p>Provide ongoing support and exceptional service to existing clients.</p>



<p>Respond promptly to inquiries received via the website, social media, CVENT, and other lead sources.</p>



<p>Conduct site tours and pre-convention meetings to support sales efforts and enhance client engagement.</p>



<p>Collaborate with internal departments to ensure event success and operational efficiency.</p>



<p>Represent the convention center by participating in industry and community-related events as necessary.</p>



<p>Support the Assistant Director of Sales and Director of Sales and Services with other duties that contribute to the center’s success.</p>



<p></p>



<p>Qualifications:<br/>To successfully perform this job, an individual must meet each essential duty's requirements to a satisfactory level. The qualifications listed below represent the necessary knowledge, skills, and abilities. Reasonable accommodation may be provided to enable individuals with disabilities to perform essential functions.</p>



<p></p>



<p>Education and Experience:</p>



<p>Bachelor’s degree in business or a related field preferred, or 3–5 years of equivalent sales experience within the tourism industry; ideally with a focus on convention center operations.</p>



<p>CMP (Certified Meeting Professional) certification is preferred.</p>



<p>Experience in contract development and negotiation is a plus.</p>



<p></p>



<p>Skills and Abilities:</p>



<p>Exceptional verbal and written communication skills, with the ability to interact effectively across all levels of staff and clientele, are required.</p>



<p>Proficiency in English (speaking, reading, and writing) required.</p>



<p>Ability to work effectively with diverse groups, both within the organization and in the community, required.</p>



<p>Demonstrated ability to work collaboratively as part of a team and independently with minimal supervision required.</p>



<p>Strong negotiation skills with the ability to identify and leverage competitive opportunities to secure new business.</p>



<p>Excellent organizational and management skills are essential.</p>



<p>Flexibility and the ability to prioritize tasks in a dynamic, fast-paced environment are critical.</p>



<p>Attention to detail required.</p>



<p>Strong problem-solving skills with a focus on organization required.</p>



<p>Commitment to delivering professional and courteous customer service required.</p>



<p>Proven track record of dependability and reliability required.</p>



<p>Professional demeanor, appearance, and adherence to high work standards required.</p>



<p>duties that contribute to the center’s success.</p>



<p></p>



<p>Technical Skills:</p>



<p>Proficiency in Microsoft Office Suite (Word, Excel, PowerPoint, Outlook) is required.</p>



<p></p>



<p>Working Conditions:</p>



<p>The physical demands described here are representative of those that must be met by an employee to successfully perform the essential functions of this job. Reasonable accommodations may be made to enable individuals with disabilities to perform essential functions.</p>



<p></p>



<p>This position is not substantially exposed to adverse conditions.  As a public assembly facility with an event-driven focus, an adjustment to work schedule may be required to coincide with events.  Infrequent travel may be required.</p>



<p></p>



<p>Note:</p>



<p>Colorado Convention Center/Legends Global is an Equal Opportunity/Affirmative Action employer and encourages Women, Minorities, Individuals with Disabilities, and protected Veterans to apply. VEVRAA Federal Contractor</p>



<p>The essential responsibilities of each position are described under the headings in the job description and may be subject to change at any time due to reasonable accommodation, or other reasons. The job description in no way states or implies that these are the only duties to be performed by the employee occupying this position. Applicants who need reasonable accommodation to complete the application process may contact 303-228-8000.</p>



<p>Employment is contingent upon new employees providing documents verifying U.S. citizenship or, for aliens, documents verifying legal permission to work in the United States.</p>



<p></p>



<p>*Employment is contingent upon successful completion of a background and credit check.</p>



Standard HTML
<p>POSITION: Sous Chef        <br/>DEPARTMENT: Food and Beverage    <br/>REPORTS TO: Executive Sous Chef     <br/>FLSA STATUS: Exempt    </p>



<p></p>



<p>LEGENDS GLOBAL</p>



<p>Legends Global is the premier partner to the world's greatest live events, venues, and brands. We deliver a fully integrated solution of premium services that keeps our partners front and center through our white-label approach.</p>



<p></p>



<p>Our network of 450 venues worldwide, hosting 20,000 events and entertaining 165 million guests each year, is powered by our depth of expertise and level of execution across every component — feasibility &amp; consulting, owner’s representation, sales, partnerships, hospitality, merchandise, venue management, and content &amp; booking — of world-class live events and venues.</p>



<p></p>



<p>The Legends Global culture is one of respect, ambitious thinking, collaboration, and bold action. We are committed to building an inclusive workplace where everyone can be authentic, make an impact, and grow their career.</p>



<p></p>



<p>Winning is an everyday thing at Legends Global. We have the best team members who understand every win is earned when we come together as one unified team. Sound like a winning formula for you? Join us!</p>



<p></p>



<p>THE ROLE<br/>Responsible for managing/overseeing production, operation, and sanitation aspects of all culinary and stewarding operations throughout Mayo Civic Center.</p>



<p></p>



<p>ESSENTIAL DUTES AND RESPONSIBILITIES</p>



<p>People and products focused hands-on management of day-to-day operations of all food outlet kitchens</p>



<p>Implement and enforce all departmental and organizational policies and procedures</p>



<p>Ensure staff compliance with all standards, policies and procedures</p>



<p>Ensure recipe compliance and quality control are met throughout the production process</p>



<p>Maintain and manage culinary and stewarding personnel to meet labor and production objectives</p>



<p>Assist Executive Chef and Executive Sous Chef, as needed, to plan innovative menus for both catering and concession</p>



<p>Oversees inventory management to ensure all outlets are always adequately supplied. Perform periodic inventory. Track waste and spoilage.</p>



<p>Maintain effective vendor relationships. Assist with product receiving and stocking, as needed</p>



<p>Oversee the sanitation standards of all kitchens to assure compliance with local health department standards and company standards.</p>



<p>Perform related duties as assigned by Management.</p>



<p></p>



<p>QUALIFICATIONS <br/>To perform this job successfully, an individual must be able to perform each essential duty with energy and enthusiasm. The requirements listed below are representative of the knowledge, skill, and/or ability required. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions. </p>



<p></p>



<p>EDUCATION AND/OR EXPERIENCE     </p>



<p>The ideal team member will have a degree or certification from an accredited culinary arts institute, or apprenticeship certification from the American Culinary Federation</p>



<p>At least two (2) to four (4) years of experience as a sous chef in a high-volume food industry</p>



<p>Proven track record in maintaining kitchen efficiencies, food quality, and production timeliness</p>



<p>Must have excellent managerial, team building and communication skills/customer service</p>



<p>Must have knowledge of kitchen sanitation, operation and maintenance of kitchen equipment</p>



<p>Must be detail-oriented and extremely organized with the ability to learn new programs and procedures quickly</p>



<p>Must be proficient in Microsoft Word, Excel, and PowerPoint</p>



<p>Must be flexible to work extended hours due to business requirements including nights, weekends and holidays</p>



<p>Must be open to providing incidental or short-term support to other facilities in the event of a business emergency</p>



<p>Travel may be required.    </p>



<p></p>



<p>LICENSES AND CERTIFICATIONS<br/>•    Serv Safe certified/Food Handlers Certificate</p>



<p></p>



<p>COMPENSATION<br/>$55,000 to $60,000 Annually<br/>Competitive hourly wage, commensurate with experience, and a generous benefits package that includes medical, dental, vision, life and disability insurance, paid vacation, and 401k plan.</p>



<p></p>



<p>WORKING CONDITIONS<br/>Location: On Site in Rochester, MN</p>



<p></p>



<p>PHYSICAL DEMANDS<br/>The physical demands described here are representative of those that must be met by an employee to successfully perform the essential functions of this job. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions.</p>



<p></p>



<p>NOTE:<br/>The essential responsibilities of this position are described under the headings above. They may be subject to change at any time due to reasonable accommodation or other reasons. Also, this document in no way states or implies that these are the only duties to be performed by the employee occupying this position. </p>



<p></p>



<p>Legends Global is an Equal Opportunity/Affirmative Action employer, and encourages Women, Minorities, Individuals with Disabilities, and protected Veterans to apply. VEVRAA Federal Contractor.</p>

Need to Standardize Divs
<p>RESPONSIBILITIES:</p>



<p>CHARACTERISTICS/QUALIFICATIONS:</p>



Need to Standardize Divs
<p>Responsibilities:</p>



<p>Requirements</p>



<p>We’re excited to offer full-time positions with fantastic benefits that support your well-being and professional growth. Here’s what you can look forward to:</p>



Standard HTML
<p>Monumental Sports &amp; Entertainment (MSE) is one of the largest integrated sports and entertainment companies in the country with one of the most diverse partnership groups in all of sports. MSE owns and operates seven major and minor sports teams: 2018 NHL Stanley Cup Champion Washington Capitals, NBA’s Washington Wizards, WNBA’s 2019 Championship Washington Mystics, NBA G League’s Capital City Go-Go, 2021 &amp; 2020 NBA 2K League Champion Wizards District Gaming and Caps Gaming, an esports sub-brand of the Capitals. Additionally, it holds a significant investment in a seventh professional team, Team Liquid, an endemic esports team owned and operated by aXiomatic, in which MSE is an investor.</p>



<p>In September 2022, MSE acquired the regional sports network, then-called NBC Sports Washington and newly rebranded as Monumental Sports Network. Monumental Sports Network now holds the exclusive local television media rights to Capitals’, Wizards’, and Mystics’ games. The network is both a linear channel and a digital operation. Prior to acquiring the linear platform, the digital platform was launched by MSE in 2016, as the first-of-its-kind regional sports network for digital, mobile, and streaming platforms. Those linear and digital platforms are now combined and join Caps Radio, Wizards Radio, MSE Outdoor and Monumental Productions for a full suite of six media enterprises.</p>



<p>In addition to Capital One Arena – a venue which hosts 3M+ visitors across over 250 events annually, MSE also manages MedStar Capitals Iceplex (training facility for the Capitals), MedStar Health Performance Center (training facility for the Wizards, Mystics, and Go-Go) and EagleBank Arena (a 12,000+ live event venue on George Mason University’s campus).</p>



<p>In July 2020, MSE partnered with William Hill (subsequently acquired by Caesars Entertainment) to open the first ever in-arena sportsbook in North America, now called Caesars Sportsbook.</p>



<p>MSE opened “District E powered by Ticketmaster” in the spring of 2023, a flagship esports and entertainment venue. This 14,000-square-foot live-event theater offers a 365-day-a-year series of immersive experiences in esports, music, culinary excellence, event programming, and community events.</p>



<p><strong>MSE proudly promotes its core values for all those that interact with the company. As a member of our team:</strong></p>



<p>The Senior Manager, Content Operations will be responsible for managing multiple systems that map, build and playback specified content for deliverable AI, scheduling software, and QR codes. This position is crucial to supporting our LED and TV systems through IPTV, in-house television production, and the department for live and pre-recorded events, including the NHL, NBA, WNBA, NCAA basketball, and other miscellaneous events.</p>



<p>Do you have strong communication and leadership skills, are detail driven, innovative, and a resourceful problem-solver?! Apply today! We would love to hear from you!</p>



<p><strong>Pay Range: </strong>$87k - $105k <strong>USD</strong>.</p>



<p><strong>Benefit Eligibility:</strong> This role is eligible to participate in health and welfare benefits.</p>



<p>We are an equal opportunity employer and all qualified applicants will receive consideration for employment without regard to race, color, religion, sex, national origin, disability status, protected veteran status, or any other characteristic protected by law.</p>



Standard HTML
<p></p>



<p><strong>Job Title:</strong></p>



<p>Facility Maintenance Technician </p>



<p><strong>Employer:</strong></p>



<p>Sabertooth Sports &amp; Entertainment (“SS&amp;E”)</p>



<p><strong>Job Location:</strong></p>



<p>F&amp;M Bank Arena (“FMBA”)</p>



<p><strong>Department:</strong></p>



<p>Operations</p>



<p><strong>Job Reports to: </strong></p>



<p>Director, Facility Operations</p>



<p><strong>Status:</strong></p>



<p>Non-exempt</p>



<p><strong>About:</strong></p>



<p>The Facility Maintenance Tech will be responsible for work involving the operation, maintenance and repair of F&amp;M Bank Arena equipment and maintenance. This includes HVAC, plumbing, electrical, lighting, life safety, automated building control system, and climate control systems as well as other mechanical equipment associated with a sports and entertainment facility.  </p>



<p><strong>Preds Perks:</strong></p>



<p>In addition to medical, dental, vision, and life insurance, (active the first of the month following hire date) all full-time employees of the SS&amp;E are eligible for the following: referral bonuses, 401K eligibility (after 1 year of employment), priority access to event presales at FMBA and Bridgestone Arena , tickets to events (when available), Nashville Locker Room (pro shop) discount, 19+ days of paid time off each year, work from home opportunities (if applicable),Ford Ice Center programming discount, on demand pay, and bonus potential.</p>



<p> </p>



<p><strong>Job Responsibilities </strong></p>



<p> </p>



<p><strong>Minimum Requirements</strong></p>



<p><strong> </strong></p>



<p><strong>Essential Physical Requirements</strong></p>



<p><strong> </strong></p>



<p><strong> </strong></p>



<p><strong>Equipment Used</strong></p>



<p> </p>



<p><em>Note: Nothing in this job description restricts management’s right to assign or reassign duties and responsibilities to this job at any time.  Employees will be required to follow any other job-related instructions and to perform any other job-related duties requested by any person authorized to give instruction or assignments.</em></p>



<p>Preds Perks: In addition to medical, dental, vision, and life insurance, all full-time employees of the Nashville Predators and entities are eligible for Preds Perks. These currently include the following: Competitive pay, referral bonuses, 401K eligibility, priority access to event presales, tickets to events (when available), Nashville Locker Room (pro shop) discount, premium pay for overnight shifts, 19+ days of paid time off each year, Ford Ice Center programming discount, on demand pay, and bonus potential.</p>



<p> </p>



<p>Equal Opportunity Employer: Nashville Predators is an equal opportunity employer. The organization does not discriminate on the basis of race, color, religion, sex (including pregnancy), sexual orientation, gender identity, national origin, age, veteran status, or disability status, genetic information, or any other applicable federal or state protected classification. The organization celebrates diversity and is committed to an inclusive environment for all employees.</p>



<p> </p>



<p>In order to ensure reasonable accommodation for individuals protected by the Americans with Disabilities Act, as amended, applicants that require accommodation in the job application process may contact our Recruitment Team at <a class="__cf_email__" data-cfemail="9fedfafcedeaf6ebfaeddfebfafef2ecf2feecf7e9f6f3f3fab1fcf0f2" href="/cdn-cgi/l/email-protection">[email protected]</a> to request an accommodation.</p>



Standard HTML
<p>Overview</p>



<p>Two powerhouse companies have joined forces to redefine excellence in sports, entertainment, and live events. Together, we combine unmatched expertise with a global reach, offering end-to-end solutions – from venue development and event booking to revenue strategy and hospitality.</p>



<p>Legends brings a 360-degree, data-driven approach across Global Partnerships, Hospitality, Merchandise, and Attractions, working with top-tier clients to deliver exceptional experiences.</p>



<p>ASM Global, the world leader in venue management and live event production, oversees 350+ iconic venues stadiums, arenas, conventions centers and theaters.</p>



<p>Our organization is committed to building an inclusive, innovative environment where differences drive solutions that benefit our team members, guests, and partners. Guided by our values of respect, integrity, and accountability, we create a workplace where everyone can succeed. Are you ready to be part of the team that is transforming live entertainment? Join us to make legends happen!</p>



<p>Global Hospitality</p>



<p>We believe that exceptional venue experiences should extend beyond game day and show time. From five -star feasts and craft cocktails to local eats and sizzling chef-inspired creations, we are renowned for our exceptional dining experiences. Our fresh, creative cuisine is just the beginning. We strive to delight guests at every turn: candy walls, inhouse bakeshops and a warm welcome at every turn.</p>



<p>Summary</p>



<p></p>



<p>Maintain the physical operation of the Branson Convention Center to ensure the total comfort of the guests. Repair and maintain all assets as needed at the Center. This position provides a high-quality catering service for banquets.</p>



<p>Essential Duties </p>



<p>Include the following. Other duties may be assigned.</p>



<p></p>



<p>Working Conditions</p>



<p></p>



<p></p>



<p>Qualifications    </p>



<p>    </p>



<p></p>



<p>Physical Demands</p>



<p></p>



<p>The physical demands described here must be met by an employee to successfully perform the essential functions of this job. Reasonable accommodations may be made to enable individuals with disabilities to perform essential functions.</p>



<p> While performing the duties of this job, the employee is regularly required to move around the facility; stand for long hours during events; talk and hear. This position may require work inside or outside of the building, as needed by events.</p>



<p>Note</p>



<p>The essential responsibilities of this position are described under the headings above.  They may be subject to change at any time due to reasonable accommodation or other reasons.  Also, this document in no way states or implies that these are the only duties to be performed by the employee occupying this position.</p>



<p>Legends Global is an Equal Opportunity/Affirmative Action employer, encouraging Women, Minorities, Individuals with Disabilities, and protected Veterans to apply. VEVRAA Federal Contractor. </p>



Standard HTML
<p>POSITION:           Accounting Manager</p>



<p>DEPARTMENT:  Finance (Accounting)</p>



<p>FLSA STATUS:    Salaried, Exempt</p>



<p></p>



<p>Summary</p>



<p>Legends, the leader in privately managed public assembly facilities, has an excellent and immediate opening for the Accounting Manager position at the Hampton Roads Convention Center. The Accounting Manager administers and manages daily activities of the accounting function at the facility by performing the following duties:</p>



<p></p>



<p>Essential Duties and Responsibilities</p>



<p>Include the following. Other duties may be assigned.</p>



<p></p>



<p></p>



<p></p>



<p>Qualifications</p>



<p>To perform this job successfully, an individual must be able to perform each essential duty satisfactorily. The requirements listed below are representative of the knowledge, skill, and/or ability required. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions.</p>



<p></p>



<p>Education and Experience</p>



<p>Skills and Abilities</p>



<p>Computer Skills</p>



<p>To perform this job successfully, an individual should have extensive knowledge of accounting software, spreadsheets, and word processing software.</p>



<p></p>



<p>Other Skills and Abilities</p>



<p></p>



<p>Physical Demands</p>



<p>The physical demands described here are representative of those that must be met by an employee to successfully perform the essential functions of this job. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions.</p>



<p>Specific vision abilities required by this job include close vision for review of statistical and other financial records and information.</p>



<p></p>



<p>Note</p>



<p>The essential responsibilities of this position are described under the headings above. They may be subject to change at any time due to reasonable accommodation or other reasons. Also, this document in no way states or implies that these are the only duties to be performed by the employee occupying this position.</p>



<p>Legends Global is an Equal Opportunity/Affirmative Action employer, and encourages Women, Minorities, Individuals with Disabilities, and protected Veterans to apply. VEVRAA Federal Contractor.</p>

Standard HTML
<p>Summary:</p>



<p>Under general supervision of the Parking Supervisor, responsible for overall supervision of parking operations during events encompassing efficient daily operations and activities in all Legends Global parking facilities.  Administers the operational facet of the division by ensuring staff preparedness for opening and closing the garages, collecting revenue, resolving problems, receiving and disseminating information and instructions, preparing reports, overseeing money, ensuring internal and public safety by performing the following duties personally and through subordinate personnel.</p>



<p></p>



<p>ESSENTIAL DUTIES AND RESPONSIBILITIES</p>



<p>Include the following. Other duties and responsibilities may be assigned.</p>



<p></p>



<p></p>



<p>Supervisory Responsibilities </p>



<p>Directly supervises employees in the Parking Department including full-time and part-time cashiers and parking attendants. Carries out supervisory responsibilities in accordance with legends Global policies and applicable laws. Responsibilities include planning, assigning, and directing work; addressing complaints and resolving problems.</p>



<p></p>



<p>QUALIFICATIONS </p>



<p>To perform this job successfully, an individual must be able to perform each essential duty satisfactorily. The requirements listed below are representative of the knowledge, skill, and/or ability required. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions of the job.</p>



<p></p>



<p>EDUCATION AND/OR EXPERIENCE</p>



<p></p>



<p>KNOWLEDGE, SKILLS &amp; ABILITIES</p>



<p>Minimal knowledge, skills and abilities required to this job:</p>



<p></p>



<p></p>



<p>CERTIFICATES, LICENSES, REGISTRATIONS</p>



<p></p>



<p></p>



<p>WORKING ENVIRONMENT</p>



<p>The working environment characteristics described here are representative of those that must be met by an employee to successfully perform the essential functions of this job. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions of the job.</p>



<p></p>



<p></p>



<p>COMPUTER SKILLS</p>



<p></p>



<p>NOTE:  The essential responsibilities of this position are described under the headings above.  They may be subject to change at any time due to reasonable accommodation or other reasons.  Also, this document in no way states or implies that these are the only duties to be performed by the employee occupying this position.</p>



<p></p>



<p>This position offers a competitive salary.  Please send a copy of your most recent resume.</p>



<p></p>



<p>Applicants that need reasonable accommodation to complete the application process may contact- 915-534-0630.</p>



<p></p>



<p>Legends Global is an Equal Opportunity/Affirmative Action employer, and encourages Women, Minorities, Individuals with Disabilities, and protected Veterans to apply. VEVRAA Federal Contractor.</p>



Standard HTML
<p>GLOBAL MERCHANDISE</p>



<p>Recognized leaders in retail and merchandising worldwide, Legends Global Merchandise provides a fully customized, customer-centric, omnichannel shopping experience for fans. Our vertical service solution allows us to provide the latest trends, styles, designs, and brand collaborations across different categories. For in-venue, e-commerce and pop-up operations, Legends sets the standard when it comes to a unique shopping experience. </p>



<p></p>



<p>We pride ourselves in creating a customized portfolio of inventory based on each property and operating as a true extension of each client’s brand.  Different guests want different things, and we are here to build and provide a tailored retail experience. </p>



<p></p>



<p>THE ROLE    </p>



<p>Directs and coordinates activities of workers engaged in onsite merchandise sales and directs/coordinates the set-up of the necessary equipment to service the event/show.  As well as, manages (balance and deposit) all revenue generated from the event in which he/she manages.</p>



<p></p>



<p>ESSENTIAL FUNCTIONS</p>



<p></p>



<p>QUALIFICATIONS</p>



<p>To perform this job successfully, the candidate must be able to perform each essential duty above at the highest levels. The requirements listed below are representative of the knowledge, skill, and/or ability required.</p>



<p></p>



<p>COMPENSATION</p>



<p>Competitive salary, commensurate with experience, and a generous benefits package that includes medical, dental, vision, life and disability insurance, paid vacation, and 401k plan.</p>



<p></p>



<p>WORKING CONDITIONS</p>



<p>Location: On Site LGM Indianapolis, IN</p>



<p></p>



<p>PHYSICAL DEMANDS</p>



<p>The physical demands described here are representative of those that must be met by an employee to successfully perform the essential functions of this job. Reasonable accommodation may be made to enable individuals with disabilities to perform the essential functions.</p>



<p></p>



<p>NOTE:</p>



<p>The essential responsibilities of this position are described below the above headings. They may be subject to change at any time due to reasonable accommodation or other reasons. Also, this document in no way states or implies that these are the only duties to be performed by the employee occupying this position.</p>



<p></p>



<p>Legends Global is an Equal Opportunity/Affirmative Action employer, and encourages Women, Minorities, Individuals with Disabilities, and protected Veterans to apply. VEVRAA Federal Contractor.</p>



<p></p>



<p></p>



Need to Standardize Divs
<p>Duties and responsibilities for the Box Office Staff include but are not limited to:</p>



<p>Qualifications:</p>



Standard HTML
<p></p>



<p></p>



<p>Essential Duties &amp; Responsibilities:</p>



<p></p>



<p>Minimum Qualifications:</p>



<p></p>



<p>Preferred Qualifications</p>



<p></p>



<p></p>



<p>Learfield offers a full spectrum of benefits for eligible employees including Medical, Dental, Vision, Health Savings Account, Life Insurance and Other Insurance Plans, Flexible Paid Time Off (minimum 10+ days annually), including Parental Leave, 20 Paid Holidays, 401(k) + Match, and Short/Long Term Disability. Leave benefits are consistent with state and local laws, including the Colorado Health Families and Workplaces Act.</p>



<p>Learfield is an Equal Opportunity Employer. We provide equal employment opportunities to applicants and employees without regard to race; color; sex; gender identity; sexual orientation; religious practices and observances; national origin; pregnancy, childbirth, or related medical conditions; status as a protected veteran or spouse/family member of a protected veteran; or disability.</p>



Standard HTML
<p>Summer Intern</p>



<p></p>



<p>About the Program</p>



<p>We’re looking for passionate, energetic interns to join us this summer for our 10-week Internship Program based in New York! During the application process, you’ll choose your top three fields of interest:</p>



<p>Finance</p>



<p>Legal</p>



<p>Hospitality Management (Food and Beverage)</p>



<p></p>



<p>Each selected intern will then be matched with a department that aligns with their interests and experience.</p>



<p></p>



<p>What You Will Do</p>



<p>Along with hands-on experience and exposure to the entertainment and hospitality industry, interns will have the opportunity to learn from company leaders, enjoy all The Seaport has to offer, and participate in career development sessions designed to prepare you for the next stage of your career.</p>



<p></p>



<p>About You</p>



<p>This program is open to rising juniors, rising seniors, and those who have graduated in the past 12-months. Current law school students are also eligible for our Legal Intern position. </p>



<p>Prior internship experience and/or relevant coursework preferred</p>



<p>Strong time management and organizational skills</p>



<p>Excellent written and verbal communication skills</p>



<p>Proficiency in Microsoft Office (Word, Excel, PowerPoint)</p>



<p>Ability to work in-person at our New York City office Mondays through Thursdays</p>



<p></p>



<p>We will reach out to qualified candidates to schedule a first-round virtual interview with a recruiter. If you’re selected to move forward, you will interview with another member of our Human Resources team before potentially interviewing with the Hiring Manager. We will contact selected candidates to extend an offer.</p>



<p></p>



<p>Compensation: $17 per hour</p>



<p>OUR BENEFITS </p>



<p></p>



<p>Taking care of our people is at the heart of everything we do and we’re committed to supporting our team with benefits that promote well-being, balance, and growth. From health and wellness to professional development and unique perks, our benefits are designed to help you thrive. Benefits may vary based on employment type and status and may include:</p>



<p> </p>



<p>Medical, dental &amp; vision coverage</p>



<p>401(k) with company match contributions</p>



<p>Life insurance coverage</p>



<p>Generous paid time off policy</p>



<p>Free family meal</p>



<p>50% employee discount at our businesses</p>



<p>A robust employee referral bonus program</p>



<p> </p>



<p>GROWTH OPPORTUNITIES</p>



<p>To us, your career is more than a job—its a journey. Whether you’re just starting your career or looking to take the next step, you’ll have access to diverse experiences within restaurants, entertainment, sports, retail, and hospitality to gain exposure across different industries and roles. Our goal is to promote from within, offering mentorship, collaboration, resources and clear paths to advancement as you build valuable skills. In our culture, growth isn’t just encouraged—it’s expected, and we’re here to support you every step of the way.</p>



<p></p>



<p></p>



<p>NOTICE TO THIRD PARTY AGENCIES</p>



<p></p>



<p>Please note that The Seaport Corporation does not accept unsolicited resumes from recruiters or employment agencies. In the absence of a signed Recruitment Fee Agreement, SEG will not consider or agree to payment of any referral compensation or recruiter fee. In the event a recruiter or agency submits a resume or candidate without a previously signed agreement, Seaport explicitly reserves the right to pursue and hire those candidate(s) without any financial obligation to the recruiter or agency. Any unsolicited resumes, including those submitted to hiring managers, are deemed to be the property of Seaport Corporation.</p>



<p></p>



<p>This job description is not meant to be an “all-inclusive” list of the duties and responsibilities of this job.  Other related duties and responsibilities may be assigned.  The Seaport Corporation reserves the right to change or modify job duties as necessary based on business necessity.</p>



<p></p>



<p>SEG participates in E-Verify to confirm that you are authorized to work in the U.S. only after a job offer is accepted and Form I-9 is completed. For more information on E-Verify, please visit the <a href="https://www.e-verify.gov/sites/default/files/everify/posters/EVerifyParticipationPoster.pdf">Everify website</a>.</p>

Standard HTML
<p>It's fun to work in a company where people truly BELIEVE in what they're doing!</p>



<p></p>



<p>We're committed to bringing passion and customer focus to the business.</p>



<p></p>



<p>JOB SUMMARY:</p>



<p>The Texas Rangers are looking for a Manager of Venue Operations to join our team! The Manager of Venue Operations is responsible for overseeing the day-to-day operations of Choctaw Stadium, Ballpark Circle, and on property tenant spaces. Their primary focus is to ensure that both proactive and reactive maintenance efforts are carried out effectively in the stadium and tenant spaces. This involves monitoring mechanical, electrical, and plumbing systems, as well as lighting, elevators, and general maintenance throughout the mentioned properties. The Manager utilizes a computerized maintenance management system (CMMS) to diligently document work orders and repairs. A key aspect of this role is collaborating closely with building tenants, maintenance, facility, grounds, security, and event departments. Additionally, the Manager reports to the Vice President of Facility Operations and maintains a strong working relationship with the Director of Engineering, facility tenants, and other departments.</p>



<p></p>



<p>ESSENTIAL FUNCTIONS OF THE POSITION INCLUDE, BUT ARE NOT LIMITED TO THE FOLLOWING:</p>



<p>Complete daily inspections, make minor repairs, and schedule other maintenance and repairs when necessary.</p>



<p>Monitors building systems and works with vendors on scheduled, preventative and emergency repairs and maintenance.</p>



<p>Deal with emergencies as they arise.</p>



<p>Communicate regularly with tenants and property management to address any building, office or tenant issues and concerns.</p>



<p>Works with department Computerized Maintenance Management System (CMMS) (work orders, inventory mgmt., preventative mgmt., etc.).</p>



<p>Provides quotes, cost estimates, and recommendations for purchases related to preventative maintenance, service, and repairs.</p>



<p>Manage and supervise 3rd party vendors, contractors, and suppliers.</p>



<p>Manage renovations, refurbishment and building projects.</p>



<p>Maintain records on all equipment.</p>



<p>Works with security department on the maintenance and repairs of the Life Safety System.</p>



<p>Assures Company is in compliance with building codes, city, state and federal safety and environmental laws, codes, standards and regulations.</p>



<p>Provide support to designated staff, in all aspects of the position; this includes, but is not limited to training, development, scheduling, and managing assigned group of employees.</p>



<p>Participate as a member of the management “on call” team to deal with the operations of the facilities as issues and problems arise 24/7 at Choctaw Stadium, Ballpark Circle, leased spaces, and if needed Globe Life Field.</p>



<p>Serves as Manager on Duty for designated events or as needed for projects and facility monitoring.</p>



<p>Excellent teamwork, self-motivator and proactive thinker.</p>



<p>All other duties as assigned.</p>



<p></p>



<p>PREFERRED QUALIFICATIONS:</p>



<p>Associates Degree in related field or equivalent experience.</p>



<p>3-5 years of general experience in facility maintenance.</p>



<p>Knowledge of general maintenance methods, operating and safety protocols related to facility management and multi-purpose venues.</p>



<p>Ability to work flexible hours to meet departmental demands/goals, which may include working nights, weekends and holidays.</p>



<p>Computer proficiency with Microsoft computer applications (Outlook, Word, Excel, PowerPoint), Computerized Maintenance Management Systems.</p>



<p>Able to read and understand blueprints and AutoCAD.</p>



<p>Demonstrate knowledge of applicable laws, codes, standards and regulations.</p>



<p>Experience in fire, life safety and emergency response procedures.</p>



<p>Ability to work well under pressure, accurately, and efficiently to meet tight deadlines, while meeting business and departmental objectives and expectations.</p>



<p>Must be professional and able to work well and communicate effectively with others.</p>



<p>Customer (internal and external) oriented self-starter.</p>



<p>Excellent oral and written communication skills.</p>



<p>Must be detail oriented with strong organizational skills and ability to multi-task.</p>



<p></p>



<p>Work Environment: </p>



<p>This position is on-call 24/7 and will require work to be performed on weekends, event nights and holidays as needed.</p>



<p>Outdoors and office environment.</p>



<p>Must be able to lift and carry up to 50 pounds.</p>



<p>Requires long periods of time on feet.</p>



<p>Ability to walk, sit, climb, crawl, kneel, squat, bend and extend arms and legs fully.</p>



<p>Ability to use hands to manipulate and effectively use tools and controls.</p>



<p>No fear of heights.</p>



<p></p>



<p>The  above  statements  are intended  to  describe  the general nature  and  level  of  work  being  performed  by  people assigned to this job.  They are not intended to be an exhaustive list of all responsibilities, duties and skills required of the job.</p>



<p><br/>If you like wild growth and working with happy, enthusiastic over-achievers, you'll enjoy your career with us!</p>



Standard HTML
<p>Who are we:<br/>A professional basketball team and state-of-the-art arena/entertainment venue that specializes in creating memorable experiences for each guest we interact with. Some of our favorite things are live sports, concerts, comedy shows, family shows, and most any other world-class event you can think of, and we’re looking for someone who shares the same interests. We live for the fast-paced world of sports &amp; live entertainment, and as such, we work hard, run fast, execute flawlessly, and party it up when it all comes together. Lastly, we strive to deliver wonderful experiences that create lasting memories, and we prefer to surround ourselves with those who are the best at what they do.</p>



<p></p>



<p>Who are you:<br/>An enthusiastic lover of sports, live entertainment, and people. You have true passion for engaging in meaningful interactions and creating memorable experiences for all guests. You strive to be helpful, engaging, and knowledgeable of all things Atlanta Hawks and State Farm Arena. You enjoy being a part of an exciting and dynamic group, and you’re committed to continuously enhancing the productivity and effectiveness of your team. Lastly, you enjoy working hard and celebrating hard, and you’d be shocked if guests weren’t positively impacted by their interactions with you.</p>



<p></p>



<p></p>



<p>The Guest Experience Specialist plays a key role in delivering a world-class experience for every guest at State Farm Arena. This role supports the implementation of fan engagement initiatives, game and event day operations, and continuous service improvements. The ideal candidate brings energy, attention to detail, and a passion for creating memorable experiences for all fans and team members. </p>



<p></p>



<p>The Guest Experience Specialist will learn, understand, and exemplify the highest level of our S.M.I.L.E culture (Southern Hospitality, Make a Moment, Individuals Matter, Listen &amp; Learn, Empowerment) as we collectively strive to create an amazing experience for our guests. S.M.I.L.E will also be significantly demonstrated in our collective efforts to train, develop, motivate, and inspire all Guest Experience part-time arena team members. The Guest Experience Specialist will report to the Senior Manager of Guest Experience. </p>



<p> </p>



<p> Key Responsibilities:</p>



<p></p>



<p> Leadership of Guest Experience Operations (50%)</p>



<p>Oversee Guest Experience operations for Atlanta Hawks games and State Farm Arena events, driving strategic initiatives that enhance service quality, team performance, and overall guest satisfaction. </p>



<p>Serve as a cultural ambassador by living the SMILE values: Southern Hospitality, Make a Moment, Individuals Matter, Listen &amp; Learn, and Empowerment. Inspire teams and elevate guest experiences through intentional leadership and authentic service. </p>



<p>Cultivate an inclusive and caring environment where employees feel valued and empowered to bring their full selves to work, driving excellence in performance and guest service </p>



<p>Support the Guest Experience Operation team with special projects, surveys, and process enhancements </p>



<p>Monitor and oversee the Guest Experience email inbox, ensuring timely responses </p>



<p> </p>



<p>Rewards and Recognition (25%)</p>



<p>Champion employee recognition initiatives that foster inclusivity, strengthen team cohesion, and celebrate individual and team achievements. </p>



<p>Develop and implement a comprehensive rewards and recognition strategy aligned with organizational goals and values </p>



<p>Facilitate feedback channels to capture employee sentiment around recognition efforts </p>



<p></p>



<p>Training and Development (25%)</p>



<p>Analyzed guest service data to uncover trends and service gaps, designing targeted action plans and cross-functional training programs that enhanced team performance and elevated overall guest satisfaction. </p>



<p>Provide evaluations, continuous feedback, and coaching to part-time team members, prioritizing development and performance improvement. This individual will lead with a coaching-first approach, fostering growth and accountability, while also managing disciplinary actions when necessary to uphold team standards and operational excellence. </p>



<p>Serve as a key contributor to the SMILE and leadership training team, facilitating engaging and impactful sessions that support team member development and drive excellence in guest experience and operations </p>



<p>Assist with conducting arena tours and support the recruiting, hiring, and training of part-time team members </p>



<p> </p>



<p>Requirements: </p>



<p>Three years or more of event or related professional experience managing part-time staff, preferably within the Sports and Entertainment Industry experience </p>



<p>Must have a flexible schedule, with the ability to work nights, weekends, and holidays as necessary</p>



<p>Proven experience leading and managing high-performing teams, including direct reports</p>



<p>Excellent written and verbal communication skills, as well as effective interpersonal skills</p>



<p>Ability to stand, sit, crouch, and bend throughout the course of daily activities</p>



<p>Must be detail-oriented and organized with an ability to multitask and adapt to change</p>



<p>Strong time management skills with a consistent track record of meeting deadlines in a fast-paced environment</p>



<p>Innovative leader with a talent for thinking big and working backward to translate vision into actionable strategies that drive meaningful results</p>



<p>Demonstrate expertise in Microsoft Office Suite, with the ability to create high-impact documents, analyze and visualize data, develop executive-level presentations, and manage communications efficiently</p>



<p>Visionary servant leader with a deep passion for empowering others and crafting exceptional guest experiences through empathy, innovation, and operational excellence</p>



<p></p>



<p>Preferred Qualifications:</p>



<p>Bachelor’s degree is preferred; however, an equivalent combination of education and experience will also be given consideration</p>



<p>Excellent leadership and communication skills, with the ability to engage and influence stakeholders at all levels</p>



<p>Performance-driven leader with a relentless focus on achieving strategic goals, fostering a culture of excellence, and maintaining uncompromising service standards</p>



<p></p>



<p></p>



<p>We are an equal opportunity employer and all qualified applicants will receive consideration for employment without regard to race, color, religion, national origin, sex, sexual orientation, age, disability, gender identity, marital or veteran status, or any other protected class.</p>



<p></p>



<p></p>



<p></p>



<p>If this opportunity looks exciting to you, please complete the application process. Go Hawks!</p>



<p></p>



<p></p>

Need to Standardize Divs
<p>Key Responsibilities</p>



<p>Qualifications</p>



Need to Standardize Divs
<p>BENEFITS &amp; PERKS</p>



<p>DUTIES AND RESPONSIBILITIES</p>



<p>QUALIFICATION REQUIREMENTS</p>



<p>KNOWLEDGE, SKILLS, ABILITIES, AND OTHER ATTRIBUTES</p>



<p>ORGANIZATIONAL CORE COMPETENCIES</p>



Standard HTML
<p></p>



<p>Delaware North Sportservice is hiring a seasonal Cook 3 to join our team at Truist Park in Atlanta, Georgia. As a Cook 3, you will demonstrate your skills and serve as a visible leader in the kitchen. Partnering with management team members, you will plan menus, deliver food to quality standards, train kitchen team members, operate kitchen equipment, ensure adherence to all health codes and sanitation regulations, and monitor quantities, labor, and overhead costs. If you are ready to make a sizzling impact and create unforgettable dining experiences, apply to join our team today.</p>



<p> </p>



<p><strong>This is a seasonal position that works during the baseball season.  The season starts in March and goes until October, pending possible playoff schedule.</strong></p>



<p>Information on our comprehensive benefits package can be found at <a href="https://careers.delawarenorth.com/whatweoffer">https://careers.delawarenorth.com/whatweoffer</a>.</p>



<p></p>



<p>We care about our team member’s personal and professional well-being. Delaware North provides a benefits package designed to give you the comfort, safety, and security you need to deliver exceptional experiences for our guests. All team members receive benefits including:</p>



<p>Eligible team members may also receive: health, dental, and vision insurance, 401(k) with company match, paid vacation days and holidays, paid parental bonding leave, employee assistance program, and tuition and/or professional certification reimbursement.</p>



<p></p>



<p></p>



<p></p>



<p></p>



<p>Days<br/>Evenings<br/>Holidays<br/>Weekends<br/>Events<br/></p>



<p>Delaware North operates concessions, premium dining, and restaurants at Trust Park dating back to 2016 when the 41,500-seat venue opened. The state-of-the-art ballpark is home to Major League Baseball's Atlanta Braves.</p>



<p>Our business is all about people, and that includes you. At Delaware North, you’re not just part of a team — you’re part of a global legacy: a family-owned company with 100+ years of history behind it. Our operations span the world, offering you unique paths to growth and success.</p>



<p>Who says you can’t love where you work? With jobs in iconic sports arenas, stunning national parks, exciting casinos, and more, we pride ourselves on giving the world great times in great places. And whether you’re interested in restaurants, hotels, sports, gaming, operations, or retail, part-time or full-time, we’re invested in helping you achieve your career goals.</p>



<p>Together, we’re shaping the future of hospitality — come grow with us!</p>



<p> Delaware North, along with its subsidiaries, is an equal opportunity employer, showcasing job opportunities and considering applicants for all positions without regard to race, color, religion, sex, gender identity, national origin, age, disability, protected veteran status, sexual orientation, or any other legally protected status. </p>



Standard HTML
<p><strong>Company Information</strong><br/>For more than 20 years, AEG has played a pivotal role in transforming sports and live entertainment. Annually, we host more than 160 million guests, promote more than 10,000 shows and present more than 22,000 events around the world. We are committed to innovation, artistry, and community, and leverage the power of our 300+ venues, leading sports franchises, marquee music brands, integrated entertainment districts, premier ticketing platform and global sponsorship activations, to create memorable moments that give the world reason to cheer.<br/><br/>Our business is interwoven with the human mind and heart, and we strive to build a diverse and inclusive company that reflects the artists, athletes, and fans that we host; reach beyond traditional boundaries to support the communities in which we operate; and minimize our impact on the environment by adopting sustainable practices throughout our business operations.<br/><br/>If you want to be challenged to up your game and make a difference, then join us in giving the world reason to cheer!</p>



<p><strong>Job Summary<br/><br/></strong>The Guest Services Representative is responsible for providing an excellent guest experience for all internal and external guests of the venue.  The incumbent monitors entry to the venue and provides guest escorts to various spaces inside the facility.<strong><br/></strong></p>



<p><strong>Essential Functions<br/></strong></p>



<p><strong>Required Qualifications</strong></p>



<p><strong>Payscale: </strong>$20.48</p>



<p><strong>Bonus: </strong><em>This position is not eligible for a bonus under the current bonus plan requirements.</em></p>



<p><strong>Benefits</strong>: <em>This position may be eligible for benefits (ACA qualification).</em></p>



<p>AEG reserves the right to change or modify the employee’s job description whether orally or in writing, at any time during the employment relationship.  AEG may require an employee to perform duties outside their normal description.</p>



<p>AEG's policy is to hire the most qualified applicants, and we comply with all applicable federal, state and local employment laws in making hiring and employee decisions.  We are an equal opportunity employer and do not discriminate against applicants or employees on the basis of race, color, marital status, disability, religion, age, sex, sexual orientation, national origin, genetic information, veteran status, or any other legally protected status recognized by applicable federal, state or local law.</p>



<p><strong><em>Employer does not offer work visa sponsorship for this position.</em></strong></p>



<p> </p>



Standard HTML
<p>For more than 20 years, AEG has played a pivotal role in transforming sports and live entertainment. Annually, we host more than 160 million guests, promote more than 10,000 shows and present more than 22,000 events around the world. We are committed to innovation, artistry, and community, and leverage the power of our 300+ venues, leading sports franchises, marquee music brands, integrated entertainment districts, premier ticketing platform and global sponsorship activations, to create memorable moments that give the world reason to cheer.<br/><br/>Our business is interwoven with the human mind and heart, and we strive to build a diverse and inclusive company that reflects the artists, athletes, and fans that we host; reach beyond traditional boundaries to support the communities in which we operate; and minimize our impact on the environment by adopting sustainable practices throughout our business operations.<br/><br/>If you want to be challenged to up your game and make a difference, then join us in giving the world reason to cheer!</p>



<p><strong>Position Summary:</strong></p>



<p>The Irrigation Technician is responsible for performing regular and preventative maintenance of facilities irrigation system, ordering irrigation supplies and helping around the facility when they are needed with turf maintenance.</p>



<p><strong><br/>Essential Functions:</strong></p>



<p><strong>Required Qualifications:</strong></p>



<p><strong>Payscale: </strong>$24.67</p>



<p><strong>Bonus: </strong><em>This position is not eligible for a bonus under the current bonus plan requirements.</em></p>



<p><strong>Benefits:</strong><em><strong>  </strong>We offer a comprehensive benefits package that includes: medical, dental and vision insurance, paid holidays, vacation and sick time, company paid basic life insurance, voluntary life insurance, parental leave, 401k Plan (with a current employer match of 3%), flexible spending and health savings account options, and wellness offerings.</em></p>



<p> </p>



<p>AEG reserves the right to change or modify the employee’s job description whether orally or in writing, at any time during the employment relationship. AEG may require an employee to perform duties outside his/her normal description.</p>



<p>AEG's policy is to hire the most qualified applicants, and we comply with all applicable federal, state and local employment laws in making hiring and employee decisions.  We are an equal opportunity employer and do not discriminate against applicants or employees on the basis of race, color, marital status, disability, religion, age, sex, sexual orientation, national origin, genetic information, veteran status, or any other legally protected status recognized by applicable federal, state or local law.</p>



<p><strong><em>Employer does not offer work visa sponsorship for this position.</em></strong></p>

Standard HTML
<p><strong>Company Information</strong><br/>For more than 20 years, AEG has played a pivotal role in transforming sports and live entertainment. Annually, we host more than 160 million guests, promote more than 10,000 shows and present more than 22,000 events around the world. We are committed to innovation, artistry, and community, and leverage the power of our 300+ venues, leading sports franchises, marquee music brands, integrated entertainment districts, premier ticketing platform and global sponsorship activations, to create memorable moments that give the world reason to cheer.<br/><br/>Our business is interwoven with the human mind and heart, and we strive to build a diverse and inclusive company that reflects the artists, athletes, and fans that we host; reach beyond traditional boundaries to support the communities in which we operate; and minimize our impact on the environment by adopting sustainable practices throughout our business operations.<br/><br/>If you want to be challenged to up your game and make a difference, then join us in giving the world reason to cheer!</p>



<p><strong>Job Summary<br/></strong>The Supervisor Security will maintain the safety and security of all employees, guests and clients at shows, events, festivals, tours, one-off's and venues through the supervision of Security Officers and by performing constant patrol, observation and documentation. The Security Supervisor and Officers will be the first point of contact for all security-related issues and will control the diffusion of any incidents at the venue. The incumbent in this position must know and enforce all rules and policies; comply with all legal and ethical instructions provided by the Security Manager and Building Management; and ensure/maintain the highest levels of integrity for him/herself and the security staff.<strong><br/></strong></p>



<p><strong>Essential Functions<br/></strong></p>



<p><strong>Required Qualifications</strong></p>



<p><strong>Payscale: </strong>$24.95</p>



<p><strong>Bonus: </strong> <strong>If not applicable</strong> <em>This position is not eligible for a bonus under the current bonus plan requirements.</em></p>



<p><strong>Benefits</strong>: <em>Part-time: This position may be eligible for benefits (ACA qualification).</em></p>



<p>AEG reserves the right to change or modify the employee’s job description whether orally or in writing, at any time during the employment relationship.  AEG may require an employee to perform duties outside their normal description.</p>



<p>AEG's policy is to hire the most qualified applicants, and we comply with all applicable federal, state and local employment laws in making hiring and employee decisions.  We are an equal opportunity employer and do not discriminate against applicants or employees on the basis of race, color, marital status, disability, religion, age, sex, sexual orientation, national origin, genetic information, veteran status, or any other legally protected status recognized by applicable federal, state or local law.</p>



<p><strong><em>Employer does not offer work visa sponsorship for this position.</em></strong></p>



<p> </p>



Standard HTML
<p></p>



<p><em>The Florida Panthers enter the 2025-26 season as the two-time defending Stanley Cup Champions, having gone to the Stanley Cup Final in each of the past three seasons. The National Hockey League’s southernmost team, the Panthers have reached the postseason in a club-record six consecutive campaigns. The Panthers operate four facilities in Broward County, Florida: Amerant Bank Arena in Sunrise, the Panthers IceDen in Coral Springs, the new state-of-the-art practice facility Baptist Health IcePlex in Fort Lauderdale, as well as the renovated War Memorial Auditorium, which hosts concerts and events for the South Florida faithful.</em></p>



<p><em> </em><em>An organization with deep roots in the community, the Panthers are owned by Vincent J. Viola, a graduate of the United States Military Academy at West Point and a veteran of the U.S. Army. Emphasizing a culture of selfless service both on and off the ice, the Panthers pillar program ‘Heroes Among Us’ honors a United States military veteran at every game and the Florida Panthers Foundation has four main focuses including veterans affairs, children's health and education, raising awareness for the endangered Florida panther and growing youth hockey.</em></p>



<p></p>



<p><strong>Job Title: Uniform Room Attendant</strong><br/><strong>Department:</strong> Concessions<br/><strong>Reports To: </strong>Concessions Manager<br/><strong>FLSA:</strong>  Non-Exempt<br/><strong>Employment Type</strong>: Part-Time<br/><strong>Location:</strong> Amerant Bank Arena</p>



<p> </p>



<p><strong>Job Summary:</strong></p>



<p>The Uniform Room Attendant will be responsible for issuing uniforms to the staff before each event and ensuring all uniforms are returned at the end of every event.  The Attendant will be responsible for ensuring the uniforms are properly cleaned, dried and hung so that all employees project a professional appearance. It will also be the responsibility of the Uniform Room Attendant to maintain the Uniform Room in a clean and organized manner.</p>



<p> </p>



<p><strong>Essential Duties and Responsibilities:</strong></p>



<p> </p>



<p>  <strong>Qualifications</strong></p>



<p> </p>



<p><strong>Position Type/Expected Hours of Work:<br/></strong>This is a non-exempt (hourly) position. Must be able to work flexible hours, nights, weekends, and holidays as needed.</p>



<p> </p>



<p> </p>



<p><em>At the Florida Panthers Hockey Club, Arena Operating Company, Panthers IceDen, Sanza Food Service, War Memorial Benefit Corporation, and FLA Team Shop, we strive to make every employee feel valued and respected for who they are and the unique contributions they make. We believe that a diverse and inclusive company is a more innovative and successful company, which is why we aim to infuse diversity, equity, and inclusion (DE&amp;I) into all aspects of our culture and our business. </em></p>



<p><em>We welcome all to apply and join our team.</em></p>



<p><em>We are an equal opportunity employer and all qualified applicants will receive consideration for employment without regard to race, color, religion, creed, gender, gender identity or expression, age, national origin or ancestry, citizenship, disability, sexual orientation, marital status, pregnancy, veteran status, membership in the uniformed services, genetic information, or any other basis protected by applicable law.</em></p>



Standard HTML
<p></p>



<p><em>The Florida Panthers enter the 2025-26 season as the two-time defending Stanley Cup Champions, having gone to the Stanley Cup Final in each of the past three seasons. The National Hockey League’s southernmost team, the Panthers have reached the postseason in a club-record six consecutive campaigns. The Panthers operate four facilities in Broward County, Florida: Amerant Bank Arena in Sunrise, the Panthers IceDen in Coral Springs, the new state-of-the-art practice facility Baptist Health IcePlex in Fort Lauderdale, as well as the renovated War Memorial Auditorium, which hosts concerts and events for the South Florida faithful.</em></p>



<p><em> </em><em>An organization with deep roots in the community, the Panthers are owned by Vincent J. Viola, a graduate of the United States Military Academy at West Point and a veteran of the U.S. Army. Emphasizing a culture of selfless service both on and off the ice, the Panthers pillar program ‘Heroes Among Us’ honors a United States military veteran at every game and the Florida Panthers Foundation has four main focuses including veterans affairs, children's health and education, raising awareness for the endangered Florida panther and growing youth hockey.</em></p>



<p></p>



<p><strong><br/>Job Title: </strong>Sous Chef<br/><strong>Department:</strong> Sanza - Main Kitchen<br/><strong>Reports To: Executive Sous Chefs</strong><br/><strong>FLSA:</strong> Exempt  <br/><strong>Employment Type</strong>: Full-Time<br/><strong>Location:</strong> Amerant Bank Arena</p>



<p><strong><br/>Job Summary:</strong><br/>The Sous Chef is the second-in-command in the kitchen, supporting the Chef in overseeing all culinary operations. This role is responsible for supervising kitchen staff, maintaining food quality and consistency, managing inventory and costs, and ensuring compliance with food safety and sanitation standards. The Sous Chef also plays a key role in menu development, staff training, and maintaining a positive and efficient work environment.</p>



<p><strong><br/>Job Functions:</strong></p>



<p>Specific duties include but are not limited to:</p>



<p><strong><br/>Qualifications:</strong></p>



<p> </p>



<p><strong>Physical Requirements:</strong></p>



<p><strong><br/>Position Type/Expected Hours of Work:<br/></strong>This is an exempt position. Must be able to work flexible hours including nights, weekends and hilidays as needed.</p>



<p> </p>



<p><em>At the Florida Panthers Hockey Club, Arena Operating Company, Panthers IceDen, Sanza Food Service, War Memorial Benefit Corporation, and FLA Team Shop, we strive to make every employee feel valued and respected for who they are and the unique contributions they make. We believe that a diverse and inclusive company is a more innovative and successful company, which is why we aim to infuse diversity, equity, and inclusion (DE&amp;I) into all aspects of our culture and our business. </em></p>



<p><em>We welcome all to apply and join our team.</em></p>



<p><em>We are an equal opportunity employer and all qualified applicants will receive consideration for employment without regard to race, color, religion, creed, gender, gender identity or expression, age, national origin or ancestry, citizenship, disability, sexual orientation, marital status, pregnancy, veteran status, membership in the uniformed services, genetic information, or any other basis protected by applicable law.</em></p>

Standard HTML
<p></p>



<p><em>The Florida Panthers enter the 2025-26 season as the two-time defending Stanley Cup Champions, having gone to the Stanley Cup Final in each of the past three seasons. The National Hockey League’s southernmost team, the Panthers have reached the postseason in a club-record six consecutive campaigns. The Panthers operate four facilities in Broward County, Florida: Amerant Bank Arena in Sunrise, the Panthers IceDen in Coral Springs, the new state-of-the-art practice facility Baptist Health IcePlex in Fort Lauderdale, as well as the renovated War Memorial Auditorium, which hosts concerts and events for the South Florida faithful.</em></p>



<p><em> </em><em>An organization with deep roots in the community, the Panthers are owned by Vincent J. Viola, a graduate of the United States Military Academy at West Point and a veteran of the U.S. Army. Emphasizing a culture of selfless service both on and off the ice, the Panthers pillar program ‘Heroes Among Us’ honors a United States military veteran at every game and the Florida Panthers Foundation has four main focuses including veterans affairs, children's health and education, raising awareness for the endangered Florida panther and growing youth hockey.</em></p>



<p></p>



<p> </p>



<p><strong>Job Title: </strong>Concession Cook<br/><strong>Department:</strong> Sanza Food Service<br/><strong>Reports To: </strong>Various Sous Chefs<br/><strong>FLSA:</strong> Non-Exempt <br/><strong>Employment Type</strong>: Part-Time <br/><strong>Location:</strong> Amerant Bank Arena<br/><br/></p>



<p><strong>Job Summary:</strong><br/>Prepare and produce quality food according to the production specs provided while adhering to all Health Department Food &amp; Safety regulations. All skill levels and experiences are welcome!</p>



<p> </p>



<p><strong>Job Functions:</strong></p>



<p>Specific duties include but are not limited to:</p>



<p><strong> </strong></p>



<p><strong>Qualifications:</strong></p>



<p> </p>



<p><strong>Position Type/Expected Hours of Work:<br/></strong>This is a part-time non-exempt position. Must have flexible hours with the ability to work nights, weekends and holidays as needed.</p>



<p> </p>



<p><em>At the Florida Panthers Hockey Club, Arena Operating Company, Panthers IceDen, Sanza Food Service, War Memorial Benefit Corporation, and FLA Team Shop, we strive to make every employee feel valued and respected for who they are and the unique contributions they make. We believe that a diverse and inclusive company is a more innovative and successful company, which is why we aim to infuse diversity, equity, and inclusion (DE&amp;I) into all aspects of our culture and our business. </em></p>



<p><em>We welcome all to apply and join our team.</em></p>



<p><em>We are an equal opportunity employer and all qualified applicants will receive consideration for employment without regard to race, color, religion, creed, gender, gender identity or expression, age, national origin or ancestry, citizenship, disability, sexual orientation, marital status, pregnancy, veteran status, membership in the uniformed services, genetic information, or any other basis protected by applicable law.</em></p>



Standard HTML
<p></p>



<p><em>The Florida Panthers enter the 2025-26 season as the two-time defending Stanley Cup Champions, having gone to the Stanley Cup Final in each of the past three seasons. The National Hockey League’s southernmost team, the Panthers have reached the postseason in a club-record six consecutive campaigns. The Panthers operate four facilities in Broward County, Florida: Amerant Bank Arena in Sunrise, the Panthers IceDen in Coral Springs, the new state-of-the-art practice facility Baptist Health IcePlex in Fort Lauderdale, as well as the renovated War Memorial Auditorium, which hosts concerts and events for the South Florida faithful.</em></p>



<p><em> </em><em>An organization with deep roots in the community, the Panthers are owned by Vincent J. Viola, a graduate of the United States Military Academy at West Point and a veteran of the U.S. Army. Emphasizing a culture of selfless service both on and off the ice, the Panthers pillar program ‘Heroes Among Us’ honors a United States military veteran at every game and the Florida Panthers Foundation has four main focuses including veterans affairs, children's health and education, raising awareness for the endangered Florida panther and growing youth hockey.</em></p>



<p></p>



<p> </p>



<p><strong>Job Title: </strong>Culinary Staff<br/><strong>Department:</strong> Sanza Food Service<br/><strong>Reports To: </strong>Kitchen Coordinator<br/><strong>FLSA:</strong> Non-Exempt<br/><strong>Employment Type</strong>: Part-Time<br/><strong>Location:</strong> Panthers Arena<br/><br/></p>



<p><strong>Job Summary:</strong><br/>Prepare and produce quality food according to the production specs provided while adhering to all Health Department Food &amp; Safety regulations. All skill levels and experiences are welcome!</p>



<p> </p>



<p><strong>Job Functions:</strong></p>



<p>Specific duties include but are not limited to:</p>



<p><strong> </strong></p>



<p><strong>Qualifications:</strong></p>



<p> </p>



<p><strong>Position Type/Expected Hours of Work:<br/></strong>This is a non-exempt part-time position. Must have flexible hours with the ability to work nights, weekends and holidays as needed.</p>



<p> </p>



<p><em>At the Florida Panthers Hockey Club, Arena Operating Company, Panthers IceDen, Sanza Food Service, War Memorial Benefit Corporation, and FLA Team Shop, we strive to make every employee feel valued and respected for who they are and the unique contributions they make. We believe that a diverse and inclusive company is a more innovative and successful company, which is why we aim to infuse diversity, equity, and inclusion (DE&amp;I) into all aspects of our culture and our business. </em></p>



<p><em>We welcome all to apply and join our team.</em></p>



<p><em>We are an equal opportunity employer and all qualified applicants will receive consideration for employment without regard to race, color, religion, creed, gender, gender identity or expression, age, national origin or ancestry, citizenship, disability, sexual orientation, marital status, pregnancy, veteran status, membership in the uniformed services, genetic information, or any other basis protected by applicable law.</em></p>



Standard HTML
<p></p>



<p><em>The Florida Panthers enter the 2025-26 season as the two-time defending Stanley Cup Champions, having gone to the Stanley Cup Final in each of the past three seasons. The National Hockey League’s southernmost team, the Panthers have reached the postseason in a club-record six consecutive campaigns. The Panthers operate four facilities in Broward County, Florida: Amerant Bank Arena in Sunrise, the Panthers IceDen in Coral Springs, the new state-of-the-art practice facility Baptist Health IcePlex in Fort Lauderdale, as well as the renovated War Memorial Auditorium, which hosts concerts and events for the South Florida faithful.</em></p>



<p><em> </em><em>An organization with deep roots in the community, the Panthers are owned by Vincent J. Viola, a graduate of the United States Military Academy at West Point and a veteran of the U.S. Army. Emphasizing a culture of selfless service both on and off the ice, the Panthers pillar program ‘Heroes Among Us’ honors a United States military veteran at every game and the Florida Panthers Foundation has four main focuses including veterans affairs, children's health and education, raising awareness for the endangered Florida panther and growing youth hockey.</em></p>



<p></p>



<p><strong><br/>Job Title: </strong>Full-Time Security Officer <strong><br/>Department: </strong>Security <strong><br/>Reports To: </strong>Supervisor of Shiift<strong><br/>FLSA: </strong>Non-Exempt <strong><br/>Employment Type:</strong> Full-Time <strong><br/>Location: </strong>Amerant Bank Arena </p>



<p> </p>



<p><strong>Job Summary:</strong> <br/>The Security Officer plays an integral role in ensuring a safe, secure, and welcoming environment to all employees and guests. Security Officers contribute to building safety by patrolling and monitoring premises and reporting safety conditions.  </p>



<p><strong> </strong></p>



<p><strong>Responsibilities Include:</strong><strong> </strong></p>



<p> </p>



<p><strong>Qualifications:</strong> </p>



<p> </p>



<p><strong>Education/Training:</strong> </p>



<p> </p>



<p><strong>Skills Required:</strong> </p>



<p> </p>



<p><strong>Physical Demands:</strong> </p>



<p> </p>



<p><strong>Position Type/Expected Hours of Work:</strong> <br/>This is an hourly non-exempt position. Must be able to work flexible hours, nights, weekends and holidays as needed.</p>



<p><em>At the Florida Panthers Hockey Club, Arena Operating Company, Panthers IceDen, Sanza Food Service, War Memorial Benefit Corporation, and FLA Team Shop, we strive to make every employee feel valued and respected for who they are and the unique contributions they make. We believe that a diverse and inclusive company is a more innovative and successful company, which is why we aim to infuse diversity, equity, and inclusion (DE&amp;I) into all aspects of our culture and our business. </em></p>



<p><em>We welcome all to apply and join our team.</em></p>



<p><em>We are an equal opportunity employer and all qualified applicants will receive consideration for employment without regard to race, color, religion, creed, gender, gender identity or expression, age, national origin or ancestry, citizenship, disability, sexual orientation, marital status, pregnancy, veteran status, membership in the uniformed services, genetic information, or any other basis protected by applicable law.</em></p>



Standard HTML
<p><strong>POSITION SUMMARY:</strong> <br/>Summer Camp Coaches will be responsible for coaching at Detroit Lions Summer Youth Football Camps throughout the state of Michigan.  Some seasonal coaches may also be involved in additional specialty football camps and clinics or Detroit Lions game day duties.</p>



<p>The hours for this position vary depending on the scheduled camp(s). This is a part-time seasonal position.  25+ camps will be conducted from June 6-August 6, 2026.  During most football camps, Summer Camp Coaches will be required to work outdoors.</p>



<p><strong>Interested candidates will need to provide their availability for the camp schedule below.  Hired candidates are able to select the camp locations of interest to them and are ultimately assigned based on staffing need.  We ask candidates consider working a MINIMUM of 5 camps during the 2026 Summer Football Camp Tour but are able to work many more.  </strong></p>



<p><strong> </strong><strong>Dates</strong><strong>                       City                                Location                               </strong>                 </p>



<p><strong> </strong></p>



<p><strong>June 6-7                   Beverly Hills                  Country Day H.S.          </strong></p>



<p><strong>June 8-11                 Hudsonville                    Eagle Stadium</strong></p>



<p><strong>June 13-14               Alpena                             Alpena H.S.</strong></p>



<p><strong>June 13-14               Petoskey                         Petoskey H.S</strong></p>



<p><strong>June 15-18               Gaylord                           Gaylord H.S.    </strong>              <strong>              </strong><strong> </strong></p>



<p><strong>June 15-18               Traverse City                 Traverse City West M.S. </strong></p>



<p><strong>June 22-25                Detroit                             Ford Field</strong></p>



<p><strong>June 23-25                Detroit                             Ford Field</strong></p>



<p><strong>June 26                     Detroit                             Ford Field</strong></p>



<p><strong>June 27-28        </strong>        <strong>Windsor</strong>                          <strong>University of Windsor</strong></p>



<p><strong>July 6-9                      Allen Park                      Lions Training Facility </strong></p>



<p><strong>July 10                       Allen Park                      Lions Training Facility </strong></p>



<p><strong>July 11                       Allen Park                      Lions Training Facility</strong></p>



<p><strong>July 11-12                  Novi                                Novi H.S. </strong></p>



<p><strong>July 12                       Allen Park                       Lions Training Facility</strong></p>



<p><strong>July 13-16                  Lake City                         Lake City H.S. </strong></p>



<p><strong>July 18-19                  Midland                           Northwood University</strong></p>



<p><strong>July 18-19                  Negaunee                        Negaunee H.S.</strong></p>



<p><strong>July 20-23                  TBD</strong></p>



<p><strong>July 25-26                  Indian River                    Inland Lakes Secondary           </strong></p>



<p><strong>July 27-30                   Mattawan                       Mattawan High School</strong></p>



<p><strong>August 1-2                  Greenville                      Greenville H.S. </strong>                          </p>



<p><strong>August 1-2</strong>                   <strong>Lansing</strong>                         <strong>Hope Sports Complex</strong></p>



<p><strong>August 3-6                   Grand Rapids               MSA Fieldhouse</strong>          </p>



<p>**Dates, times and locations subject to change (Schedule finalized by March 1, 2026)</p>



<p><strong>ESSENTIAL FUNCTIONS (including, but not limited to):<br/></strong>The Summer Camp Coach position will have daily responsibilities including, without limitation, the following:</p>



<p><strong>NONESSENTIAL FUNCTIONS:</strong></p>



<p><strong>QUALIFICATIONS/REQUIREMENTS:</strong></p>

Standard HTML
<p>The Detroit Lions currently have an opening for a <strong>Production Intern</strong>. Reporting to the Production Manager, the Production Intern will be responsible for supporting media content for all Detroit Lions content platforms. This will include videography, editing and overall production of engaging video content for the team’s digital properties as well as facilitation of ongoing media availability sessions.</p>



<p>The Production Intern is a season-long role supporting the 2026 football season, with an anticipated end in January 2027, with potential for post-season extension. Candidates will need to be able to work 5 days per week plus some weekends. Due to the unique nature of this position, the candidate must be able to work extended hours during the NFL season and training camp, which will include working on nights, weekends, and holidays.</p>



<p>This position is based in the Meijer Performance center in Allen Park, MI, but will also require travel to Ford Field and various off-site locations.</p>



<p><strong>ESSENTIAL FUNCTIONS (including, but not limited to):<br/></strong>The Production Intern will have daily responsibilities including, without limitation, the following:</p>



<p><strong>NONESSENTIAL FUNCTIONS:</strong></p>



<p><strong> </strong><strong>QUALIFICATIONS/REQUIREMENTS:</strong></p>



Standard HTML
<p></p>



<p><em>The Florida Panthers enter the 2025-26 season as the two-time defending Stanley Cup Champions, having gone to the Stanley Cup Final in each of the past three seasons. The National Hockey League’s southernmost team, the Panthers have reached the postseason in a club-record six consecutive campaigns. The Panthers operate four facilities in Broward County, Florida: Amerant Bank Arena in Sunrise, the Panthers IceDen in Coral Springs, the new state-of-the-art practice facility Baptist Health IcePlex in Fort Lauderdale, as well as the renovated War Memorial Auditorium, which hosts concerts and events for the South Florida faithful.</em></p>



<p><em> </em><em>An organization with deep roots in the community, the Panthers are owned by Vincent J. Viola, a graduate of the United States Military Academy at West Point and a veteran of the U.S. Army. Emphasizing a culture of selfless service both on and off the ice, the Panthers pillar program ‘Heroes Among Us’ honors a United States military veteran at every game and the Florida Panthers Foundation has four main focuses including veterans affairs, children's health and education, raising awareness for the endangered Florida panther and growing youth hockey.</em></p>



<p></p>



<p> </p>



<p><strong>Job Title: </strong>Part-Time Conversion Crew<br/><strong>Department:</strong> Arena Operations<br/><strong>Reports To: </strong>Conversion Crew Supervisor<br/><strong>FLSA:</strong> Non-Exempt<br/><strong>Employment Type</strong>: Part-Time<br/><strong>Location:</strong> Amerant Bank Arena</p>



<p><br/><strong>Job Summary:</strong></p>



<p>Responsible for performing work as needed to Set-up, maintain, convert and prepare for events at the Amerant Bank Arena.</p>



<p> </p>



<p><strong>Essential Functions: </strong></p>



<p><strong> </strong></p>



<p><strong>Qualifications:</strong></p>



<p><strong> </strong></p>



<p><strong>Work Environment:</strong></p>



<p>This position works in an arena where the noise level is generally high, crowd traffic is heavy, temperatures are variable – often cold; lights are bright or dark with occasional exposure to flashing lights and pyrotechnics.</p>



<p> </p>



<p><strong>Physical Demands:</strong></p>



<p><strong>Balancing -</strong> Maintaining body equilibrium to prevent falling and walking, standing or crouching on narrow, slippery, or erratically moving surfaces.<br/><strong>Stooping -</strong> Bending body downward and forward by bending spine at the waist.<br/><strong>Kneeling -</strong> Bending legs at knee to come to a rest on knee or knees.<br/><strong>Crouching -</strong> Bending the body downward and forward by bending leg and spine.<br/><strong>Reaching -</strong> Extending hand(s) and arm(s) in any direction.|<br/><strong>Standing -</strong> Particularly for sustained periods of time.<br/><strong>Walking -</strong> Moving about on foot to accomplish tasks, particularly for long distances or moving from one work site to another.<br/><strong>Pushing -</strong> Using upper extremities to press against something with steady force in order to thrust forward, downward or outward.<br/><strong>Pulling -</strong> Using upper extremities to exert force in order to draw, haul or tug objects in a sustained motion.<br/><strong>Lifting -</strong> Raising objects up to 65 pounds from a lower to a higher position or moving objects horizontally from position-to-position.<br/><strong>Grasping -</strong> Applying pressure to an object with the fingers and palm.<br/><strong>Talking -</strong> Expressing or exchanging ideas by means of the spoken word.<br/><strong>Hearing -</strong> Perceiving the nature of sounds at normal speaking levels with or without correction. Ability to receive detailed information through oral communication, and to make the discriminations in sound.<br/><strong>Repetitive motion -</strong> Substantial movements (motions) of the wrists, hands, and/or fingers.</p>



<p> </p>



<p><strong>Position Type/Expected Hours of Work:</strong></p>



<p>This is a part-time position. Must be able to work traditional hours in addition to nights, weekends and occasional holidays.</p>



<p>.</p>



<p><em>At the Florida Panthers Hockey Club, Arena Operating Company, Panthers IceDen, Sanza Food Service, War Memorial Benefit Corporation, and FLA Team Shop, we strive to make every employee feel valued and respected for who they are and the unique contributions they make. We believe that a diverse and inclusive company is a more innovative and successful company, which is why we aim to infuse diversity, equity, and inclusion (DE&amp;I) into all aspects of our culture and our business. </em></p>



<p><em>We welcome all to apply and join our team.</em></p>



<p><em>We are an equal opportunity employer and all qualified applicants will receive consideration for employment without regard to race, color, religion, creed, gender, gender identity or expression, age, national origin or ancestry, citizenship, disability, sexual orientation, marital status, pregnancy, veteran status, membership in the uniformed services, genetic information, or any other basis protected by applicable law.</em></p>



Standard HTML
<p>The <strong>Head of Mascot Programming</strong> is a full-time position is responsible for performing as the Detroit Lions team Mascot, Roary, and overseeing all mascot-related programming including the scheduling of appearances and social media presence.</p>



<p><strong>ESSENTIAL FUNCTIONS:<br/></strong>The Mascot position will have daily responsibilities including, without limitation, the following:</p>



<p><strong> </strong><strong>NONESSENTIAL FUNCTIONS:</strong></p>



<p><strong> </strong><strong>QUALIFICATIONS/REQUIREMENTS:</strong></p>



<p> </p>



Standard HTML
<p></p>



<p><strong>Benefits and Wellness Senior Specialist</strong></p>



<p><strong>Department: </strong>Human Resources</p>



<p><strong>Reports To: </strong>Vice President – Human Resources</p>



<p><strong>Job Classification:</strong> Non-Exempt</p>



<p><strong> </strong></p>



<p><strong>Description:</strong></p>



<p>We are seeking a detail-oriented and empathetic Benefits and Wellness Senior Specialist to lead the administration and strategic evolution of the New York Yankees’ benefits program including health, wellness, retirement plans, and leave of absence administration for our domestic and international staff. This role will act as the first point of contact for all Yankees’ employees, serve as primary contact for vendors and third-party administrators, and will ensure our benefits remain competitive, compliant and deeply valued by our employees.</p>



<p><strong> </strong></p>



<p><strong>Primary Responsibilities:</strong></p>



<p><strong> </strong></p>



<p><strong>Qualifications and Experience:</strong></p>



<p><em> The salary range for this position is $85,000 - $110,000 per year plus a comprehensive benefits package.</em></p>



<p><em>This description is intended to describe the type of work being performed by a person assigned to this position. It is not an exhaustive list of all duties and responsibilities required of the employee. The New York Yankees are an Equal Opportunity Employer. The Company is committed to the principles of equal employment opportunity for all employees and applicants for employment</em>.</p>



<p><br/></p>



<p><br/></p>



<p><br/></p>



Standard HTML
<p>Nothing is more powerful and gratifying than being a part of something bigger than yourself. Bring your dedicated purpose and undeniable passion to the Indianapolis Colts. We are on a journey to build the best organization in football. People are our greatest assets and we’re looking for our next cohort of MVPs.</p>



<p><strong> </strong></p>



<p>We are seeking a Training Camp Intern to contribute to the Indianapolis Colts off-site training camp. This role will support the Football Operations department by planning and executing the Club’s training camp move and daily operation. You will make integral contributions as a Colts team member and will gain real hands-on experience and exposure to an NFL organization.</p>



<p> </p>



<p>The Training Camp Intern will report to the Director of Football Operations and collaborate with other departments and business partners throughout the internship.</p>



<p> </p>



<p><strong>GENERAL RESPONSIBILITIES</strong></p>



<p>Training Camp duties and responsibilities include but are not limited to the following:</p>



<p><strong> </strong></p>



<p><strong>QUALIFICATIONS</strong></p>



<p> </p>



<p>We are an equal opportunity employer and all qualified applicants will receive consideration for employment without regard to race, color, religion, sex, national origin, disability status, protected veteran status, or any other characteristic protected by law. </p>

Need to Standardize Divs
<p>Keynote Speaker Session:</p>



<p>Organizations Scheduled to Attend So Far:</p>



Need to Standardize Divs
<p>Required:</p>



<p>Preferred:</p>



<p>Core Competencies</p>



Need to Standardize Divs
<p>Roles and Responsibilities</p>



<p>Do you want to be a superstar in the sports business? That’s the first qualification. If you answered yes, then answer two more questions: 1) do you have a strong work ethic, and 2) do you have a desire to learn and excel?</p>



<p>Benefits &amp; Compensation</p>



Need to Standardize Divs
<p>Roles and Responsibilities</p>



<p>Do you want to be a superstar in the sports business? That’s the first qualification. If you answered yes, then answer two more questions: 1) do you have a strong work ethic, and 2) do you have a desire to learn and excel?</p>



<p>Benefits &amp; Compensation</p>



Need to Standardize Divs
<p>Sponsorship Sales &amp; Partnerships:</p>



<p>Ticket Sales &amp; Fan Engagement:</p>



<p>Additional Revenue Streams:</p>



<p>Game Day &amp; Event Operations</p>



<p>Community &amp; Public Relations</p>



<p>Team &amp; Staff Management</p>



<p>General Team Responsibilities</p>



<p>Knowledge, Skills &amp; Abilities</p>



<p>Benefits &amp; Compensation</p>



Need to Standardize Divs
<p>Role &amp; Responsibilities:</p>



<p>Expectations:</p>



<p>Required Skills:</p>



<p>Educational Requirements</p>



Need to Standardize Divs
<p>What You’ll Do:</p>



<p>What You’ll Need:</p>



<p>We’re excited to offer full-time positions with fantastic benefits that support your well-being and professional growth. Here’s what you can look forward to:</p>



Need to Standardize Divs
<p>Role &amp; Responsibilities:</p>



<p>Expectations:</p>



<p>Required Skills:</p>



<p>Educational Requirements:</p>



Need to Standardize Divs
<p>Human Resources Management</p>



<p>SCGA Board of Directors &amp; Committee Activity</p>



<p>Organizational Leadership</p>



<p>To perform the job successfully, the Director, Governance &amp; Administration must demonstrate the following skills, abilities and competencies:</p>



<p>Education and Experience (Preferred):</p>



<p>We’re excited to offer full-time positions with fantastic benefits that support your well-being and professional growth. Here’s what you can look forward to:</p>



Standard HTML
<p>POSITION: Executive Chef  </p>



<p>DEPARTMENT: Food &amp; Beverage </p>



<p>FLSA STATUS: Exempt</p>



<p></p>



<p>LEGENDS GLOBAL</p>



<p>Legends Global is the premier partner to the world's greatest live events, venues, and brands. We deliver a fully integrated solution of premium services that keeps our partners front and center through our white-label approach. Our network of 450 venues worldwide, hosting 20,000 events and entertaining 165 million guests each year, is powered by our depth of expertise and level of execution across every component — feasibility &amp; consulting, owner’s representation, sales, partnerships, hospitality, merchandise, venue management, and content &amp; booking — of world-class live events and venues.</p>



<p></p>



<p>The Legends Global culture is one of respect, ambitious thinking, collaboration, and bold action. We are committed to building an inclusive workplace where everyone can be authentic, make an impact, and grow their career. Winning is an everyday thing at Legends Global. We have the best team members who understand every win is earned when we come together as one unified team. Sound like a winning formula for you? Join us!</p>



<p></p>



<p>Essential Duties and Responsibilities</p>



<p>Research and develop of menu items to keep pace with industry trends, local and seasonal ingredients to support restaurant and concession business.</p>



<p>Inspect recipe compliance and quality control are met throughout the production process.</p>



<p>Maintain health department score of 90 or above and SAVOR’S 3rd party audit score of 95 or above.</p>



<p>Create the production schedule to meet business demands.</p>



<p>Manage department budget to meet and exceed labor and cost of good expenditures.</p>



<p>Maintains an active role in local hospitality community and professional associations.</p>



<p>Fiduciary responsibility to operate at peak efficiencies maximizing labor cost of goods and supplies.</p>



<p>Maintaining all kitchen equipment cleanliness and annual maintenance.</p>



<p>Continually manage, monitor, and seek labor efficiencies to reduce costs, improve product output and enhance overall guess experience.</p>



<p>Hiring and Training of all kitchen and stewarding staff to in clued “Serve safe” and any Health department regulations.</p>



<p>Maintain and manage culinary and stewarding personnel to meet labor and production objectives. Ordering, receiving, and preparing all food items.</p>



<p>Maintaining food costs and budget goals.</p>



<p>Produce required product according to Banquet Event Orders for each event.</p>



<p>Develop proposals for potential clients, to include tastings on larger plated events.</p>



<p>Entertain prospective clients through Chef’s tables.</p>



<p>Maintains an active role in local hospitality community and professional associations.</p>



<p>Develop creative menus with food presentations and maintain a quality product.</p>



<p></p>



<p>Supervisory Responsibilities </p>



<p>Carries out supervisory responsibilities in accordance with all Legends policies and applicable laws. Responsibilities include interviewing, hiring, and training employees; planning, assigning, and directing work; appraising performance; rewarding and disciplining employees; addressing complaints and resolving problems.</p>



<p></p>



<p>Qualifications </p>



<p>To perform this job successfully, an individual must be able to perform each essential duty with energy and enthusiasm. The requirements listed below are representative of the knowledge, skill, and/or ability required. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions.</p>



<p></p>



<p>Education and/or Experience</p>



<p>Must have a High School Diploma or GED.</p>



<p>Minimum of 8 years of culinary experience in high volume facility producing meals for large events.</p>



<p></p>



<p>Skills and Abilities</p>



<p>Must maintain local Health Codes and sanitation HACCP.</p>



<p>Excellent organizational and planning skills.</p>



<p>Excellent communication and interpersonal skills.</p>



<p>Strong customer service orientation.</p>



<p>Ability to work with limited supervision.</p>



<p>Ability to interact with all levels of staff including management.</p>



<p>Ability to work irregular hours as dictated by the event schedule, including nights, weekends, and holidays.</p>



<p></p>



<p>LICENSES &amp; CERTIFICATIONS</p>



<p>Serve-safe certified/Food Handlers Certificate</p>



<p></p>



<p>COMPENSATION</p>



<p>Competitive salary, commensurate with experience, and a generous benefits package that includes medical, dental, vision, life and disability insurance, paid vacation, and 401k plan.</p>



<p>Range: $110k-$115k</p>



<p></p>



<p>WORKING CONDITIONS</p>



<p>Location: On Site </p>



<p></p>



<p>Physical Demands</p>



<p>The physical demands described here are representative of those that must be met by an employee to successfully perform the essential functions of this job. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions.</p>



<p></p>



<p>NOTE:</p>



<p>The essential responsibilities of this position are described under the headings above. They may be subject to change at any time due to reasonable accommodation or other reasons. Also, this document in no way states or implies that these are the only duties to be performed by the employee occupying this position.</p>



<p></p>



<p>Legends Global is an Equal Opportunity/Affirmative Action employer, and encourages Women, Minorities, Individuals with Disabilities, and protected Veterans to apply. VEVRAA Federal Contractor</p>



Standard HTML
<p>POSITION:  Accounting Manager      </p>



<p>DEPARTMENT:  Finance         </p>



<p>REPORTS TO:  General Manager      </p>



<p>FLSA STATUS:  Exempt          </p>



<p></p>



<p>LEGENDS GLOBAL</p>



<p>Legends Global is the premier partner to the world's greatest live events, venues, and brands. We deliver a fully integrated solution of premium services that keeps our partners front and center through our white-label approach.</p>



<p></p>



<p>Our network of 450 venues worldwide, hosting 20,000 events and entertaining 165 million guests each year, is powered by our depth of expertise and level of execution across every component — feasibility &amp; consulting, owner’s representation, sales, partnerships, hospitality, merchandise, venue management, and content &amp; booking — of world-class live events and venues.</p>



<p></p>



<p>The Legends Global culture is one of respect, ambitious thinking, collaboration, and bold action. We are committed to building an inclusive workplace where everyone can be authentic, make an impact, and grow their career.</p>



<p></p>



<p>Winning is an everyday thing at Legends Global. We have the best team members who understand every win is earned when we come together as one unified team. Sound like a winning formula for you. Join us!</p>



<p></p>



<p>THE ROLE</p>



<p>The Accounting Manager is responsible for overseeing and managing the daily operations of the accounting function at the facility. This role ensures the accuracy and integrity of financial reporting, maintains effective internal controls, and supports the financial health of the venue. The Accounting Manager partners with operational departments to align financial performance with business goals and is responsible for payroll processing and compliance.</p>



<p></p>



<p>Essential Duties and Responsibilities</p>



<p></p>



<p>Supervisory Responsibilities </p>



<p>Carries out supervisory responsibilities in accordance with all Legends Global policies and applicable laws. Responsibilities include interviewing, hiring, and training employees; planning, assigning, and directing work; appraising performance; rewarding and disciplining employees; addressing complaints and resolving problems.</p>



<p></p>



<p>Qualifications </p>



<p>To perform this job successfully, an individual must be able to perform each essential duty with energy and enthusiasm. The requirements listed below are representative of the knowledge, skill, and/or ability required. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions.</p>



<p></p>



<p>Education and/or Experience          </p>



<p></p>



<p>Skills and Abilities  </p>



<p>Computer Skills</p>



<p></p>



<p>COMPENSATION</p>



<p>Competitive salary, commensurate with experience, and a generous benefits package that includes medical, dental, vision, life and disability insurance, paid vacation, and 401k plan.</p>



<p></p>



<p>WORKING CONDITIONS</p>



<p>Location: On Site Charles F. Dodge City Center</p>



<p></p>



<p>PHYSICAL DEMANDS</p>



<p>The physical demands described here are representative of those that must be met by an employee to successfully perform the essential functions of this job. Reasonable accommodations may be made to enable individuals with disabilities to perform the essential functions.</p>



<p></p>



<p>NOTE:</p>



<p>The essential responsibilities of this position are described under the headings above. They may be subject to change at any time due to reasonable accommodation or other reasons. Also, this document in no way states or implies that these are the only duties to be performed by the employee occupying this position.</p>



<p></p>



<p>Legends Global is an Equal Opportunity/Affirmative Action employer, and encourages Women, Minorities, Individuals with Disabilities, and protected Veterans to apply. VEVRAA Federal Contractor.</p>



<p></p>



<p></p>

Need to Standardize Divs
<p>The West Henderson Fieldhouse will feature:</p>



<p>Qualifications:</p>



Standard HTML
<p><strong>About IMG Academy</strong><br/>Named one of the Best and Brightest Companies to Work For in the Nation in 2024, IMG Academy is the world's leading sports education brand, providing a holistic education model that empowers student-athletes to win their future, preparing them for college and for life. IMG Academy provides growth opportunities for all student-athletes through an innovative suite of on-campus and online experiences:  </p>



<p><strong>Position Summary: </strong>The <strong>Tennis Operations Coordinator </strong>is the key operational support leader ensuring smooth execution of tennis program logistics, athlete experience, event coordination, and administrative systems.</p>



<p><strong>Key Responsibilities:</strong></p>



<p><strong>Knowledge, Skills and Abilities:</strong>   </p>



<p><strong>Preferred Skills</strong>:</p>



<p> <strong>Physical Demands and Work Environment:</strong></p>



<p>#LI-NS1</p>



<p><strong>Background Requirements: </strong> </p>



<p>Don’t meet every single requirement? We are dedicated to building a diverse, inclusive, authentic workplace, so if you’re excited about this role but your past experience doesn’t align perfectly with every qualification in the job description, we encourage you to apply anyway. You may be just the right candidate for this or other roles.  </p>



<p> </p>



<p><strong>Get to know us better:</strong>  </p>



<p><a href="http://www.imgacademy.com/">www.imgacademy.com</a> </p>



<p><a href="http://www.imgacademy.com/careers">www.imgacademy.com/careers</a> </p>



<p><strong> </strong> </p>



<p>IMG Academy provides equal employment opportunities to all employees and applicants for employment and prohibits discrimination and harassment of any type without regard to race, color, religion, age, sex, national origin, disability status, genetics, protected veteran status, sexual orientation, gender identity or expression, or any other characteristic protected by federal, state or local laws.</p>



Standard HTML
<p><strong>About IMG Academy</strong><br/>Named one of the Best and Brightest Companies to Work For in the Nation in 2024, IMG Academy is the world's leading sports education brand, providing a holistic education model that empowers student-athletes to win their future, preparing them for college and for life. IMG Academy provides growth opportunities for all student-athletes through an innovative suite of on-campus and online experiences:  </p>



<p><strong>Position Summary</strong>: As an Assistant Girls' Lacrosse Coach at IMG Academy, you will play an essential role in developing high-performing student-athletes both on and off the field. This position offers the opportunity to be part of an environment that emphasizes character, discipline, academic achievement, and athletic excellence. You will help us continue to build a culture of success.</p>



<p><strong>Key Responsibilities:</strong></p>



<p><strong>Ideal Candidate Profile:</strong></p>



<p>#LI-NS1 </p>



<p><strong>Background Requirements: </strong> </p>



<p>Don’t meet every single requirement? We are dedicated to building a diverse, inclusive, authentic workplace, so if you’re excited about this role but your past experience doesn’t align perfectly with every qualification in the job description, we encourage you to apply anyway. You may be just the right candidate for this or other roles.  </p>



<p> </p>



<p><strong>Get to know us better:</strong>  </p>



<p><a href="http://www.imgacademy.com/">www.imgacademy.com</a> </p>



<p><a href="http://www.imgacademy.com/careers">www.imgacademy.com/careers</a> </p>



<p><strong> </strong> </p>



<p>IMG Academy provides equal employment opportunities to all employees and applicants for employment and prohibits discrimination and harassment of any type without regard to race, color, religion, age, sex, national origin, disability status, genetics, protected veteran status, sexual orientation, gender identity or expression, or any other characteristic protected by federal, state or local laws.</p>



Standard HTML
<p><strong>About IMG Academy</strong><br/>Named one of the Best and Brightest Companies to Work For in the Nation in 2024, IMG Academy is the world's leading sports education brand, providing a holistic education model that empowers student-athletes to win their future, preparing them for college and for life. IMG Academy provides growth opportunities for all student-athletes through an innovative suite of on-campus and online experiences:  </p>



<p><strong>Position Overview: </strong>IMG Academy is seeking a highly motivated and detail-oriented <strong>Assistant Football Coach – Defensive Line</strong> to join the Junior National Football Program. This coach will be responsible for the technical development, physical preparation, and personal growth of student-athletes competing at a national level, while supporting the overall mission and standards of IMG Academy Football.</p>



<p><strong>Essential Duties &amp; Responsibilities:</strong></p>



<p><strong>On-Field Coaching &amp; Player Development:</strong></p>



<p><strong>Program &amp; Team Support:</strong></p>



<p><strong>Student-Athlete Development:</strong></p>



<p><strong>Administrative &amp; Operational Responsibilities:</strong></p>



<p><strong>Required Qualifications:</strong></p>



<p><strong>Preferred Qualifications:</strong></p>



<p><strong>Key Competencies:</strong></p>



<p><strong>Physical Demands and Work Environment:</strong></p>



<p>#LI-NS1</p>



<p> </p>



<p><strong>Background Requirements: </strong> </p>



<p>Don’t meet every single requirement? We are dedicated to building a diverse, inclusive, authentic workplace, so if you’re excited about this role but your past experience doesn’t align perfectly with every qualification in the job description, we encourage you to apply anyway. You may be just the right candidate for this or other roles.  </p>



<p> </p>



<p><strong>Get to know us better:</strong>  </p>



<p><a href="http://www.imgacademy.com/">www.imgacademy.com</a> </p>



<p><a href="http://www.imgacademy.com/careers">www.imgacademy.com/careers</a> </p>



<p><strong> </strong> </p>



<p>IMG Academy provides equal employment opportunities to all employees and applicants for employment and prohibits discrimination and harassment of any type without regard to race, color, religion, age, sex, national origin, disability status, genetics, protected veteran status, sexual orientation, gender identity or expression, or any other characteristic protected by federal, state or local laws.</p>



Need to Standardize Divs
<p>Proof We Are Awesome:</p>



<p>Lead Coach responsibilities include, but are not limited to:</p>



<p>“WOW” Us With ...</p>



Need to Standardize Divs
Standard HTML
<p></p>



<p>Join the team at Hershey Country Club, a private, premier golf and recreation club. The club’s rich history of accolades, success, and chocolate combine to form a one-of-a-kind experience for individuals and families of all ages, and features 45 holes of golf on the championship East &amp; West courses. </p>



<p>This position is responsible for setting up and tearing down meeting and banquet rooms at the Hershey Country Club.</p>



<p>As a Part-Time Team Member, you will enjoy sweet perks like FREE admission and parking to Hersheypark, discounts on food &amp; shopping, and more as soon as you receive your Employee ID!</p>



<p><strong>Job Duties (Duties marked with an asterisk are essential functions of this job):</strong></p>



<p>Setting up and tearing down meeting and banquet rooms including tables, chairs, meeting equipment, lectern, etc.</p>



<p>Vacuuming and maintaining overall cleanliness of function rooms</p>



<p>Provide assistance to clients with moving boxes and supplies to meeting rooms</p>



<p>Vacuuming carpets and dusting chairs in the function rooms during set up</p>



<p>Setting up outside functions, including tables and chairs for meals and golf functions</p>



<p>Setting up exhibit tables and other equipment required per the client's requests</p>



<p>Maintaining neat and clean storerooms</p>



<p>Taking equipment to maintenance for necessary repairs</p>



<p>Reporting areas or items that need attention to the manager on duty</p>



<p>Setting up basic audio/visual equipment when required</p>



<p>Cleaning and refreshing meeting rooms during the meeting breaks</p>



<p>Picking up and returning borrowed equipment from other divisions</p>



<p>Maintaining clean and organized storage areas with tables, chairs, and Audio Visual aids.</p>



<p>Perform other duties as assigned</p>



<p><strong>Qualifications:</strong></p>



<p>Must be at least 18 years of age or older.</p>



<p>Must have a valid driver’s license</p>



<p><strong>Knowledge, Skills, and Abilities:</strong></p>



<p>Experience with audio/visual equipment preferred</p>



<p>Ability to work independently and handle multiple priorities</p>



<p>Ability to communicate and follow instructions verbally and in writing</p>



<p>Ability to work safely and follow safety procedures</p>



<p>Embody our company's values, Selfless Spirit of Service, Devoted to our Legacy, Respectful of Others, Team Focused.</p>



<p>Must have guest-oriented attitude and ability to work well with others</p>



<p><strong>Job Demands:</strong></p>



<p>While performing the duties of this job, the employee is required to:</p>



<p>Normal shifts include 7:00 a.m.-3:30 p.m., 3:00 p.m.-11:30 p.m., and 11:00 p.m.-7:30 a.m. Weekends, holidays, and some overtime required. Shifts may vary according to business needs.</p>



<p>Must be able to work nights</p>



<p>Physical conditions include considerable walking and bending, ability to lift 50 lbs., and proper use of chemicals.</p>



<p>Proper footwear must be provided by employee.</p>



<p>Will also be required to perform these duties outdoors in a golf course environment</p>



<p>This is a union position and the work schedule will be based on union seniority.  Candidates must be able to meet scheduled requirements, which will most likely require evening and weekend hours.</p>



<p><strong>Nothing in this job description restricts management’s right to assign or reassign duties and responsibilities to this job at any time.</strong></p>



<p><strong>Hershey Entertainment and Resorts is an Equal Opportunity Employer</strong></p>



<p>Equal Opportunity Employer<br/>
This employer is required to notify all applicants of their rights pursuant to federal employment laws.
For further information, please review the <a href="https://www.eeoc.gov/poster">Know Your Rights</a> notice from the Department of Labor.</p>

Standard HTML
<p></p>



<p>Join the team at Hershey Lodge, an award-winning resort best known for being warm, welcoming, and distinctly Hershey. Offering 665 guest rooms and 100,000 square feet of function space, Hershey Lodge provides convenience and comfort for families and guests of all ages. We hope you'll enjoy the sweet hospitality and iconic chocolate details around every corner.</p>



<p>This position is responsible for all aspects of food service and guest satisfaction with the Bears' Den restaurant located at the Hershey Lodge. </p>



<p>As a Part-Time Team Member, you will enjoy sweet perks like FREE admission and parking to Hersheypark, discounts on food &amp; shopping, and more as soon as you receive your Employee ID!</p>



<p><strong>Job Duties (Duties marked with an asterisk are essential functions of this job):</strong></p>



<p>Greeting all guests in a friendly, efficient, and timely manner </p>



<p>Having a thorough knowledge of all menu and related items to include wine service </p>



<p>Having the ability to master and fully utilize the Point of Sale service system </p>



<p>Assisting all staff members in operation of the dining room</p>



<p>Accomplishing other duties as required.   </p>



<p><strong>Qualifications:</strong></p>



<p>Must be at least 18 years of age. </p>



<p>Must be able to complete RAMP training by passing the test within the negotiated probation period. </p>



<p><strong>Knowledge, Skills, and Abilities:</strong></p>



<p>Must present a clean and professional image. </p>



<p>Must demonstrate an ability to work with and function with the Point of Sale and related systems and with elementary math. </p>



<p>Must be able to balance cash drawers and prepare the necessary paperwork. </p>



<p>Must be able to communicate to guests and staff effectively. </p>



<p><strong>Job Demands:</strong></p>



<p>The working schedule for this position may include days, evenings, weekends, and holidays based on operational needs. </p>



<p>Ability to work a flexible eight-hour shift including breakfast, lunch, and dinner shifts according to operational needs, including weekends and holidays. </p>



<p>Must be able to work on one's feet for long periods of time </p>



<p>Must be able to stoop, bend, push and lift up to 40 pounds. </p>



<p>Must work in a clean, efficient, and orderly manner. </p>



<p>This is a union position and the work schedule will be based on union seniority. Candidates must be able to meet scheduled requirements, which will most likely require evening and weekend hours. </p>



<p><strong>Nothing in this job description restricts management’s right to assign or reassign duties and responsibilities to this job at any time.</strong></p>



<p><strong>Hershey Entertainment and Resorts is an Equal Opportunity Employer</strong></p>



<p>Equal Opportunity Employer<br/>
This employer is required to notify all applicants of their rights pursuant to federal employment laws.
For further information, please review the <a href="https://www.eeoc.gov/poster">Know Your Rights</a> notice from the Department of Labor.</p>



Standard HTML
<p></p>



<p>Be part of the opening team at Hershey Social Restaurant + Bar, downtown Hershey’s newest restaurant and bar. Located near the iconic intersection of Cocoa and Chocolate Avenue, Hershey Social features bold flavors, signature cocktails, and over-the-top desserts inspired by Hershey’s chocolate roots.</p>



<p>This position is responsible for maintaining the bar areas, equipment, and assisting in the service of food and beverage to guests in a high-paced environment.</p>



<p>As a Part-Time Team Member, you will enjoy sweet perks like FREE admission and parking to Hersheypark, discounts on food &amp; shopping, and more as soon as you receive your Employee ID!</p>



<p><strong>Job Duties (Duties marked with an asterisk are essential functions of this job):</strong></p>



<p>Responsible for setup, service of the bar, and storage areas.</p>



<p>Anticipate guests’ needs by answering questions pertaining to wine, liquor, and cocktail menus.</p>



<p>Abide by all state and federal liquor regulations pertaining to serving alcoholic beverages to minors and intoxicated guests.</p>



<p>Maintain stock and cleanliness of the bar area including counters, floors, refrigerators, and removal of trash.</p>



<p>Monitor shelves and coolers to ensure proper stocking of beer, wine, liquor, and other beverages.</p>



<p>Assist servers and bartenders with duties such as mixing drinks, serving guests, detailing, and breakdown of the bar area.</p>



<p>Assist with the inventory process on a monthly basis.</p>



<p>Assist with filling and delivering requisitioned products and equipment.</p>



<p>Maintain a commitment to exceptional guest service.</p>



<p>Restock bar area with clean glasses and other accessories.</p>



<p>Assist the manager with liquor pick-ups as well as the ordering process.</p>



<p>Perform other duties as assigned</p>



<p><strong>Qualifications:</strong></p>



<p>Must be at least 18 years of age or older</p>



<p>Must be able to complete RAMP certification training</p>



<p><strong>Knowledge, Skills, and Abilities:</strong></p>



<p>1 year of restaurant experience preferred</p>



<p>Bartending experience preferred</p>



<p><strong>Job Demands:</strong></p>



<p>Must be able to work a flexible schedule including days, evenings, weekends, and holidays</p>



<p>Must be able to lift up to 70 lbs</p>



<p>Must be able to stand for up to 8 hours</p>



<p><strong>Nothing in this job description restricts management’s right to assign or reassign duties and responsibilities to this job at any time.</strong></p>



<p><strong>Hershey Entertainment and Resorts is an Equal Opportunity Employer.</strong></p>



<p>Equal Opportunity Employer<br/>
This employer is required to notify all applicants of their rights pursuant to federal employment laws.
For further information, please review the <a href="https://www.eeoc.gov/poster">Know Your Rights</a> notice from the Department of Labor.</p>



Standard HTML
<p></p>



<p>Devon Seafood + Steak - Comfortably upscale and refined. Devon provides the perfect atmosphere for guests to enjoy simply prepared seafood sourced globally and premium steaks. Our wine cellar offers an award winning wine list and handcrafted cocktails that complement a one-of-a-kind dining experience.</p>



<p>This position is responsible for assisting servers with the service of food and beverages to guests, and maintaining a neat and orderly dining room and the guest service area.</p>



<p>As a Part-Time Team Member, you will enjoy sweet perks like FREE admission and parking to Hersheypark, discounts on food &amp; shopping, and more as soon as you receive your Employee ID!</p>



<p><strong>Job Duties (Duties marked with an asterisk are essential functions of this job):</strong></p>



<p><strong>Qualifications:</strong></p>



<p><strong>Knowledge, Skills, and Abilities:</strong></p>



<p><strong>Job Demands:</strong></p>



<p><strong>Nothing in this job description restricts management’s right to assign or reassign duties and responsibilities to this job at any time.</strong></p>



<p><strong>Hershey Entertainment and Resorts is an Equal Opportunity Employer.</strong></p>



<p>Equal Opportunity Employer<br/>
This employer is required to notify all applicants of their rights pursuant to federal employment laws.
For further information, please review the <a href="https://www.eeoc.gov/poster">Know Your Rights</a> notice from the Department of Labor.</p>



Standard HTML
<p></p>



<p>Devon Seafood + Steak - Comfortably upscale and refined. Devon provides the perfect atmosphere for guests to enjoy simply prepared seafood sourced globally and premium steaks. Our wine cellar offers an award winning wine list and handcrafted cocktails that complement a one-of-a-kind dining experience.</p>



<p>This position is responsible for greeting guests, seating guests, and coordinating reservations within dining room areas of Devon Seafood + Steak.</p>



<p>As a Part-Time Team Member, you will enjoy sweet perks like FREE admission and parking to Hersheypark, discounts on food &amp; shopping, and more as soon as you receive your Employee ID!</p>



<p><strong>Job Duties (Duties marked with an asterisk are essential functions of this job):</strong></p>



<p>Open the doors as guests enter the restaurant, when possible.</p>



<p>Greet guests immediately upon entering the restaurant.</p>



<p>Seat guests at tables in a friendly and timely manner.</p>



<p>Complete wait sheets accurately.</p>



<p>Complete table count sheets accurately.</p>



<p>Answer the telephone.</p>



<p>Meet guests' needs by providing pertinent information about the restaurant, menu items, and surrounding area.</p>



<p>Thank guests as they are leaving.</p>



<p>Use specified techniques to satisfy unhappy guests.</p>



<p>Open doors for guests as they exit the restaurant.</p>



<p>Handle to-go orders on an as needed basis.</p>



<p>Maintain guests' needs throughout their dining experience by assisting servers with pre-bussing procedures.</p>



<p>Use a sanitizing solution to wipe down tables, chairs, booths, and table bases to assist servers.</p>



<p>Sweep floor area around table to assist servers as needed.</p>



<p>Reset using designated silverware, napkins, and condiments to assist servers as needed.</p>



<p>Stock all items on the Front Desk Checklist. </p>



<p>Perform other duties as assigned.</p>



<p><strong>Qualifications:</strong></p>



<p>Must be 16 years of age or older</p>



<p><strong>Knowledge, Skills, and Abilities:</strong></p>



<p>Strong interpersonal and verbal communication skills to interact in a positive manner with co-workers, guests, and the general public.</p>



<p>Able to read, write, and perform addition/subtraction calculations.</p>



<p><strong>Job Demands:</strong></p>



<p>Able to see at a distance (20 feet) , at close range (12 inches), distinguish between shapes, and utilize peripheral vision to avoid potential hazards.</p>



<p>Exposure to chemicals.</p>



<p>Physical requirements include standing (up to 100% of shift), walking, bending, stooping, lifting, reaching, and finger dexterity.</p>



<p>Ability to communicate effectively in a loud environment.</p>



<p>This is a part-time, year round position. The working schedule for this position may be flexible to include days, evenings, weekends, and holidays based on operational needs.</p>



<p><strong>Nothing in this job description restricts management’s right to assign or reassign duties and responsibilities to this job at any time.</strong></p>



<p><strong>Hershey Entertainment and Resorts is an Equal Opportunity Employer.</strong></p>



<p>Equal Opportunity Employer<br/>
This employer is required to notify all applicants of their rights pursuant to federal employment laws.
For further information, please review the <a href="https://www.eeoc.gov/poster">Know Your Rights</a> notice from the Department of Labor.</p>



Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'

Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'
Error during job scrape: 'NoneType' object has no attribute 'find_all'

In [202]:
temp_df = pd.DataFrame(jobs_list)
temp_df['details']

0           Figure Skating Business Operations & Inn...
1                                      Essential Fun...
2                 Empty DataFrame
Columns: []
Index: []
3                                        Why join ou...
4                      ESSENTIAL DUTES AND RESPONSIB...
5        Why the Colorado Convention Center is a gre...
6                     ESSENTIAL DUTES AND RESPONSIBI...
7                                         RESPONSIBI...
8                                         Responsibi...
9       MSE proudly promotes its core values for all...
10                                    Job Responsibi...
11       Include the following. Other duties may be ...
12      Include the following. Other duties may be a...
13                                                  ...
14                                      ESSENTIAL FU...
15      Duties and responsibilities for the Box Offi...
16                     Essential Duties & Responsibi...
17      We’re looking for passionate, energetic inte...
18       ESSENTIAL FUNCTIONS OF THE POSITION INCLUDE...
19                Empty DataFrame
Columns: []
Index: []
20                                    Key Responsibi...
21                                        BENEFITS &...
22      We care about our team member’s personal and...
23                                     Essential Fun...
24                                    Essential Func...
25                                      Essential Fu...
26                  Essential Duties and Responsibil...
27         Specific duties include but are not limit...
28          Specific duties include but are not limi...
29          Specific duties include but are not limi...
30                               Responsibilities In...
31       ESSENTIAL FUNCTIONS (including, but not lim...
32       ESSENTIAL FUNCTIONS (including, but not lim...
33                                    Essential Func...
34       ESSENTIAL FUNCTIONS:The Mascot position wil...
35                               Primary Responsibil...
36      Training Camp duties and responsibilities in...
37                                 Keynote Speaker S...
38                                               Req...
39                               Roles and Responsib...
40                               Roles and Responsib...
41                       Sponsorship Sales & Partner...
42                                Role & Responsibil...
43                                          What You...
44                                Role & Responsibil...
45                               Human Resources Man...
46                    Essential Duties and Responsib...
47                    Essential Duties and Responsib...
48             The West Henderson Fieldhouse will fe...
49       About IMG AcademyNamed one of the Best and ...
50       About IMG AcademyNamed one of the Best and ...
51      About IMG AcademyNamed one of the Best and B...
52                                    Proof We Are A...
53                Empty DataFrame
Columns: []
Index: []
54       Job Duties (Duties marked with an asterisk ...
55      Job Duties (Duties marked with an asterisk a...
56       Job Duties (Duties marked with an asterisk ...
57      Job Duties (Duties marked with an asterisk a...
58       Job Duties (Duties marked with an asterisk ...
Name: details, dtype: object

In [97]:
team_work_df = pd.DataFrame(jobs_list)

team_work_df['city'] = team_work_df['location_info'].str.split('·').str[0].str.strip()
team_work_df['state'] = team_work_df['location_info'].str.split('·').str[1].str.strip()

In [110]:
team_work_df.loc[team_work_df['state'].str.len()>2,['title','location_info','city']]

,title,location_info,city
91,HR Business Partner,London · United Kingdom · Hybrid,London
98,"Major Gift Officer, West Coast",CA · Remote,CA
131,Event Operations + Merchandising Intern,FL · Hybrid,FL
132,Event Merchandising Manager (On-Site),FL · Hybrid,FL
134,Creative Strategist,United States · Remote,United States
135,Account Executive,United States · Remote,United States
231,Event Operations + Merchandising Intern,FL · Hybrid,FL
232,Event Merchandising Manager (On-Site),FL · Hybrid,FL
234,Creative Strategist,United States · Remote,United States
235,Account Executive,United States · Remote,United States
331,Event Operations + Merchandising Intern,FL · Hybrid,FL
332,Event Merchandising Manager (On-Site),FL · Hybrid,FL
334,Creative Strategist,United States · Remote,United States
335,Account Executive,United States · Remote,United States

In [25]:
# Will use this once deployed pages = ((1,3),(3,5),(5,7),(7,9),(9,11))
pages = ((1,3))
for page_range in pages:
    for page_ind in range(page_range[0],page_range[1]):
        recent_jobs_html = extract(page_ind)
        transorm(recent_jobs_html)

1
2
3
4
5
6
7
8
9
10

In [12]:
### This is a copy of scaper code so I can split up some processing

all_jobs = soup.find_all(class_ = "browse-jobs-card")

for job in all_jobs:
##################################################################### Scraping Basic info from Job cards ####################################################
    
    logo_image = job.find('img').get('src')
    job_url = 'https://www.teamworkonline.com' + job.find('a').get('href')
    title = job.find(class_ = "margin-none").get_text().strip()
    company = job.find(class_ = "browse-jobs-card__content--organization").get_text().strip()
    location_info = job.find(class_ = "trending__content--small").get_text().strip()
    # Will need to split as such location_info.split('·')[0])
    experience = job.find(class_ = "browse-jobs-card__content--small").get_text().strip()
    
################################################### Scraping time based info from Job cards and doing minor calcualtions ####################################
    posting_number_list = job.find_all(class_ = "browse-jobs-card__scoreboard")
    posting_numbers = posting_number_list[0].get_text().strip() + posting_number_list[1].get_text().strip()
    posting_date_identifier = job.find(class_ = "trending__content--small trending__scoreboard--time margin-left--xx-small").get_text().strip().split(' ')[0]
    if posting_date_identifier.endswith('s'):
        pass
    else:
        posting_date_identifier = posting_date_identifier + ('s')
    posting_timestamp = datetime.now() - timedelta(**{posting_date_identifier: int(posting_numbers)})

'02/27/2026 12:58:28'

tests

In [20]:
######################### OLD CODE - N0 LONGER USED BUT KEPT BECAUSE ALOT OF WORK ##########################################

#.find_all(['p','strong']) •
data = {}
headers = []
for section in job_details:
    if (p_tag):
        full_text = section
        
        if section.find('strong'):
            header = section.find('strong').get_text()
            content = section.find_next_sibling()
        else:
            header = ''
            content = ''
    else:
        full_text = wrap_bullets(section.get_text(separator = '\n'))
        print(type(full_text))
    #for br in section.find_all('br'):
    #    br.replace_with("\n")
    
    #full_text = section.get_text(separator = '\n')
    if not full_text:
        continue
    
    #print(full_text)
    #header_text,details = extract_bullets_from_text(full_text,header,content)
    
    #if header_text and details:
    #    headers.append(header_text)
    #    data[header_text] = details
    #else:
    details = []
    print('HELPPPPP')
    if type(full_text) == list:
        print('list')
    else:
        print('one tag')
        
    header_text = full_text.get_text()
    next_tag = full_text.find_next_sibling()
    
    if (next_tag and next_tag.name in ['ul', 'ol']):
        headers.append(header_text)
        items = next_tag.find_all('li')
        details = [item.get_text(strip=True) for item in items]
    
        data[header_text] = details 
            

# Convert to single-row DataFrame
df = pd.DataFrame({k: pd.Series(v) for k, v in data.items()})
print(df)


def extract_bullets_from_text(text,strong_header,strong_content):
    """Extract header and bullets from text"""
    print(text)
    print('\n\n\n')
    try:
        if strong_content and strong_header:
            header = strong_header
            content = strong_content.get_text().strip()
            print(header)
        else:
            if ':' in text:
                sections = text.split(':')
                #print(sections)
                header = sections[0].strip()
                content = sections[1:]
                #if sections[1].strip() != '' else header
                #print(content)
            elif '\n' in text:
                sections = text.split('\n', 1)
                #print(sections)
                #print('\n\n')
                header = sections[0].strip()
                content = sections[1].strip() if sections[1].strip() != '' else header
                
                
        if header and content:
            bullets = re.split(r'[-•·*]\s*', content)
            
            if len(bullets) <= 1:
                bullets = re.split(r'-\s+', content)
            
            bullets = [b.strip() for b in bullets if b.strip()]
            
            if bullets:
                return (header, bullets)
        
    except:
        print('Error')
        pass
    
    return (None, None)

AttributeError: 'str' object has no attribute 'get_text'